// <auto-generated />
// Regenerate: dotnet run --project codegen/Novolis.Raylib.CodeGen -- generate
// ManifestSha256: dba996b53aae31ef6fea3e5b08c97e848c09f48ec454a5b2d27003c12c97ae66
#nullable enable
using System.Drawing;
using System.Runtime.CompilerServices;

namespace Novolis.Raylib;
/// <summary>
/// raygui immediate-mode widgets (UTF-8); draw after scene and HUD, before EndDrawing.
/// </summary>
public static partial class Gui
{
    /// <summary>
    /// Enables raygui controls (global state).
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void Enable() => GuiControls.Enable();
    /// <summary>
    /// Disables raygui controls (global state).
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void Disable() => GuiControls.Disable();
    /// <summary>
    /// Locks raygui controls (global state).
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void Lock() => GuiControls.Lock();
    /// <summary>
    /// Unlocks raygui controls (global state).
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void Unlock() => GuiControls.Unlock();
    /// <summary>
    /// Sets global raygui alpha.
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void SetAlpha(float alpha) => GuiControls.SetAlpha(alpha);
    /// <summary>
    /// Loads default raygui style.
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void LoadStyleDefault() => GuiControls.LoadStyleDefault();
    /// <summary>
    /// raygui button; returns true when pressed.
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static bool Button(RectangleF bounds, string label) => GuiControls.Button(bounds, label);
    /// <summary>
    /// raygui static label.
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void Label(RectangleF bounds, string text) => GuiControls.Label(bounds, text);
    /// <summary>
    /// raygui panel with title.
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static bool Panel(RectangleF bounds, string title) => GuiControls.Panel(bounds, title);
    /// <summary>
    /// raygui group box with title.
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void GroupBox(RectangleF bounds, string title) => GuiControls.GroupBox(bounds, title);
    /// <summary>
    /// raygui toggle control.
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static bool Toggle(RectangleF bounds, string label, ref bool active) => GuiControls.Toggle(bounds, label, ref active);
    /// <summary>
    /// raygui checkbox.
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static bool CheckBox(RectangleF bounds, string label, ref bool active) => GuiControls.CheckBox(bounds, label, ref active);
    /// <summary>
    /// raygui combo box.
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static bool ComboBox(RectangleF bounds, string text, ref int active) => GuiControls.ComboBox(bounds, text, ref active);
    /// <summary>
    /// raygui slider with label.
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static bool Slider(RectangleF bounds, string label, ref float value, float min, float max) => GuiControls.Slider(bounds, label, ref value, min, max);
    /// <summary>
    /// raygui slider bar with label.
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static bool SliderBar(RectangleF bounds, string label, ref float value, float min, float max) => GuiControls.SliderBar(bounds, label, ref value, min, max);
    /// <summary>
    /// raygui progress bar with label.
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static bool ProgressBar(RectangleF bounds, string label, ref float value, float min, float max) => GuiControls.ProgressBar(bounds, label, ref value, min, max);
}
