// <auto-generated />
// Regenerate: dotnet run --project codegen/Novolis.Raylib.CodeGen -- generate
// ManifestSha256: a34ca8d46a5faf6263fc5c83acec030ea5022604de3b923711a029d76edda766
#nullable enable
using System.Drawing;
using System.Runtime.CompilerServices;

namespace Novolis.Raylib;
public static partial class Gui
{
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void Enable() => GuiControls.Enable();
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void Disable() => GuiControls.Disable();
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void Lock() => GuiControls.Lock();
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void Unlock() => GuiControls.Unlock();
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void SetAlpha(float alpha) => GuiControls.SetAlpha(alpha);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void LoadStyleDefault() => GuiControls.LoadStyleDefault();
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static bool Button(RectangleF bounds, string label) => GuiControls.Button(bounds, label);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void Label(RectangleF bounds, string text) => GuiControls.Label(bounds, text);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static bool Panel(RectangleF bounds, string title) => GuiControls.Panel(bounds, title);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void GroupBox(RectangleF bounds, string title) => GuiControls.GroupBox(bounds, title);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static bool Toggle(RectangleF bounds, string label, ref bool active) => GuiControls.Toggle(bounds, label, ref active);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static bool CheckBox(RectangleF bounds, string label, ref bool active) => GuiControls.CheckBox(bounds, label, ref active);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static bool ComboBox(RectangleF bounds, string text, ref int active) => GuiControls.ComboBox(bounds, text, ref active);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static bool Slider(RectangleF bounds, string label, ref float value, float min, float max) => GuiControls.Slider(bounds, label, ref value, min, max);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static bool SliderBar(RectangleF bounds, string label, ref float value, float min, float max) => GuiControls.SliderBar(bounds, label, ref value, min, max);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static bool ProgressBar(RectangleF bounds, string label, ref float value, float min, float max) => GuiControls.ProgressBar(bounds, label, ref value, min, max);
}
