// <auto-generated />
// Regenerate: dotnet run --project codegen/Novolis.Raylib.CodeGen -- generate
// ManifestSha256: c5e666aec25c3034bc5d2639dfce85ebd4bbda7b7c587047807104cb5129bf3b
#nullable enable
using System.Drawing;
using System.Numerics;
using Novolis.Raylib.Interop;
using System.Runtime.CompilerServices;

namespace Novolis.Raylib.Rendering;
public static partial class World3D
{
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void Begin(Camera3D camera) => Raylib6Native.BeginMode3D(camera);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void End() => Raylib6Native.EndMode3D();
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void DrawCube(Vector3 position, float width, float height, float length, Color color) => Raylib6Native.DrawCube(position, width, height, length, color.ToRaylibColor());
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void DrawCubeV(Vector3 position, Vector3 size, Color color) => Raylib6Native.DrawCubeV(position, size, color.ToRaylibColor());
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void DrawCubeWiresV(Vector3 position, Vector3 size, Color color) => Raylib6Native.DrawCubeWiresV(position, size, color.ToRaylibColor());
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void DrawSphere(Vector3 centerPos, float radius, Color color) => Raylib6Native.DrawSphere(centerPos, radius, color.ToRaylibColor());
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void DrawSphereWires(Vector3 centerPos, float radius, int rings, int slices, Color color) => Raylib6Native.DrawSphereWires(centerPos, radius, rings, slices, color.ToRaylibColor());
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void DrawLine3D(Vector3 startPos, Vector3 endPos, Color color) => Raylib6Native.DrawLine3D(startPos, endPos, color.ToRaylibColor());
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void DrawCylinder(Vector3 position, float radiusTop, float radiusBottom, float height, int slices, Color color) => Raylib6Native.DrawCylinder(position, radiusTop, radiusBottom, height, slices, color.ToRaylibColor());
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void DrawGrid(int slices, float spacing) => Raylib6Native.DrawGrid(slices, spacing);
}
