// <auto-generated />
// Regenerate: dotnet run --project codegen/Novolis.Raylib.CodeGen -- generate
// ManifestSha256: 236b8c99b94d01d9e81759f998ea28215bf160148765da11922594f993fe0f28
#nullable enable
using System.Numerics;
using Novolis.Raylib.Interop;
using System.Runtime.CompilerServices;

namespace Novolis.Raylib.Interact;
public static partial class Input
{
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static bool IsKeyPressed(KeyboardKey key) => Raylib6Native.IsKeyPressed((int)key);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static bool IsKeyDown(KeyboardKey key) => Raylib6Native.IsKeyDown((int)key);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static bool IsKeyReleased(KeyboardKey key) => Raylib6Native.IsKeyReleased((int)key);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    /// <summary>
    /// Unicode codepoint from the last key pressed with Alt or Ctrl (raylib GetCharPressed).
    /// </summary>
    public static int GetCharPressed() => Raylib6Native.GetCharPressed();
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    /// <summary>
    /// Next keycode from the key queue (raylib GetKeyPressed); returns 0 when empty.
    /// </summary>
    public static int GetKeyPressed() => Raylib6Native.GetKeyPressed();
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static bool IsCursorOnScreen() => Raylib6Native.IsCursorOnScreen();
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static bool IsMouseButtonPressed(MouseButton button) => Raylib6Native.IsMouseButtonPressed((int)button);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static bool IsMouseButtonDown(MouseButton button) => Raylib6Native.IsMouseButtonDown((int)button);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static float GetMouseWheelMove() => Raylib6Native.GetMouseWheelMove();
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static Vector2 GetMousePosition() => Raylib6Native.GetMousePosition();
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static Vector2 GetMouseDelta() => Raylib6Native.GetMouseDelta();
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void DisableCursor() => Raylib6Native.DisableCursor();
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void EnableCursor() => Raylib6Native.EnableCursor();
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void SetMousePosition(int x, int y) => Raylib6Native.SetMousePosition(x, y);
}
