// <auto-generated />
// Regenerate: dotnet run --project codegen/Novolis.Raylib.CodeGen -- generate
// ManifestSha256: 3414d24bb780080d0017c425bd7ec2e0353c54aef0598ae22f908c6d8bea1506
#nullable enable
using System.Numerics;
using Novolis.Raylib.Interop;
using System.Runtime.CompilerServices;

namespace Novolis.Raylib.Interact;
/// <summary>
/// Keyboard, mouse, and cursor input.
/// </summary>
public static partial class Input
{
    /// <summary>
    /// Check if a key has been pressed once
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static bool IsKeyPressed(KeyboardKey key) => Raylib6Native.IsKeyPressed((int)key);
    /// <summary>
    /// Check if a key is being pressed
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static bool IsKeyDown(KeyboardKey key) => Raylib6Native.IsKeyDown((int)key);
    /// <summary>
    /// Check if a key has been released once
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static bool IsKeyReleased(KeyboardKey key) => Raylib6Native.IsKeyReleased((int)key);
    /// <summary>
    /// Unicode codepoint from the last key pressed with Alt or Ctrl (raylib GetCharPressed).
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static int GetCharPressed() => Raylib6Native.GetCharPressed();
    /// <summary>
    /// Next keycode from the key queue (raylib GetKeyPressed); returns 0 when empty.
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static int GetKeyPressed() => Raylib6Native.GetKeyPressed();
    /// <summary>
    /// Check if cursor is on the screen
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static bool IsCursorOnScreen() => Raylib6Native.IsCursorOnScreen();
    /// <summary>
    /// Check if a mouse button has been pressed once
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static bool IsMouseButtonPressed(MouseButton button) => Raylib6Native.IsMouseButtonPressed((int)button);
    /// <summary>
    /// Check if a mouse button is being pressed
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static bool IsMouseButtonDown(MouseButton button) => Raylib6Native.IsMouseButtonDown((int)button);
    /// <summary>
    /// Get mouse wheel movement for X or Y, whichever is larger
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static float GetMouseWheelMove() => Raylib6Native.GetMouseWheelMove();
    /// <summary>
    /// Get mouse position XY
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static Vector2 GetMousePosition() => Raylib6Native.GetMousePosition();
    /// <summary>
    /// Get mouse delta between frames
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static Vector2 GetMouseDelta() => Raylib6Native.GetMouseDelta();
    /// <summary>
    /// Disables cursor (lock cursor)
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void DisableCursor() => Raylib6Native.DisableCursor();
    /// <summary>
    /// Enables cursor (unlock cursor)
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void EnableCursor() => Raylib6Native.EnableCursor();
    /// <summary>
    /// Set mouse position XY
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void SetMousePosition(int x, int y) => Raylib6Native.SetMousePosition(x, y);
}
