// <auto-generated />
// Regenerate: dotnet run --project codegen/Novolis.Raylib.CodeGen -- generate
// ManifestSha256: 3414d24bb780080d0017c425bd7ec2e0353c54aef0598ae22f908c6d8bea1506
#nullable enable
using System.Drawing;
using Novolis.Raylib.Interop;
using System.Runtime.CompilerServices;

namespace Novolis.Raylib.Rendering;
/// <summary>
/// 2D drawing and framebuffer operations (raylib drawing module).
/// </summary>
public static partial class Graphics
{
    /// <summary>
    /// Setup canvas (framebuffer) to start drawing
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void BeginDrawing() => Raylib6Native.BeginDrawing();
    /// <summary>
    /// End canvas drawing and swap buffers (double buffering)
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void EndDrawing()
    {
        Raylib6Native.EndDrawing();
        RaylibDebugFrameHooks.NotifyAfterEndDrawing();
    }

    /// <summary>
    /// Set background color (framebuffer clear color)
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void ClearBackground(Color color) => Raylib6Native.ClearBackground(color.ToRaylibColor());
    /// <summary>
    /// Draw text (using default font)
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void DrawText(string text, int posX, int posY, int fontSize, Color color) => Raylib6Native.DrawText(text, posX, posY, fontSize, color.ToRaylibColor());
    /// <summary>
    /// Measure string width for default font
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static int MeasureText(string text, int fontSize) => Raylib6Native.MeasureText(text, fontSize);
    /// <summary>
    /// Draw a color-filled rectangle
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void DrawRectangle(int posX, int posY, int width, int height, Color color) => Raylib6Native.DrawRectangle(posX, posY, width, height, color.ToRaylibColor());
    /// <summary>
    /// Draw a color-filled rectangle
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void DrawRectangleRec(RectangleF rec, Color color) => Raylib6Native.DrawRectangleRec(rec, color.ToRaylibColor());
    /// <summary>
    /// Draw rectangle outline
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void DrawRectangleLines(int posX, int posY, int width, int height, Color color) => Raylib6Native.DrawRectangleLines(posX, posY, width, height, color.ToRaylibColor());
    /// <summary>
    /// Draw a line
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void DrawLine(int startPosX, int startPosY, int endPosX, int endPosY, Color color) => Raylib6Native.DrawLine(startPosX, startPosY, endPosX, endPosY, color.ToRaylibColor());
    /// <summary>
    /// Begin scissor mode (define screen area for following drawing)
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void BeginScissorMode(int x, int y, int width, int height) => Raylib6Native.BeginScissorMode(x, y, width, height);
    /// <summary>
    /// End scissor mode
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void EndScissorMode() => Raylib6Native.EndScissorMode();
    /// <summary>
    /// Draw a color-filled circle
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void DrawCircle(int centerX, int centerY, float radius, Color color) => Raylib6Native.DrawCircle(centerX, centerY, radius, color.ToRaylibColor());
    /// <summary>
    /// Draw current FPS
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void DrawFPS(int posX, int posY) => Raylib6Native.DrawFPS(posX, posY);
}
