// <auto-generated />
// Regenerate: dotnet run --project codegen/Novolis.Raylib.CodeGen -- generate
// ManifestSha256: 236b8c99b94d01d9e81759f998ea28215bf160148765da11922594f993fe0f28
#nullable enable
using System.Drawing;
using Novolis.Raylib.Interop;
using System.Runtime.CompilerServices;

namespace Novolis.Raylib.Rendering;
public static partial class Graphics
{
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void BeginDrawing() => Raylib6Native.BeginDrawing();
    public static void EndDrawing()
    {
        Raylib6Native.EndDrawing();
        RaylibDebugFrameHooks.NotifyAfterEndDrawing();
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void ClearBackground(Color color) => Raylib6Native.ClearBackground(color.ToRaylibColor());
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void DrawText(string text, int posX, int posY, int fontSize, Color color) => Raylib6Native.DrawText(text, posX, posY, fontSize, color.ToRaylibColor());
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static int MeasureText(string text, int fontSize) => Raylib6Native.MeasureText(text, fontSize);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void DrawRectangle(int posX, int posY, int width, int height, Color color) => Raylib6Native.DrawRectangle(posX, posY, width, height, color.ToRaylibColor());
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void DrawRectangleRec(RectangleF rec, Color color) => Raylib6Native.DrawRectangleRec(rec, color.ToRaylibColor());
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void DrawRectangleLines(int posX, int posY, int width, int height, Color color) => Raylib6Native.DrawRectangleLines(posX, posY, width, height, color.ToRaylibColor());
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void DrawLine(int startPosX, int startPosY, int endPosX, int endPosY, Color color) => Raylib6Native.DrawLine(startPosX, startPosY, endPosX, endPosY, color.ToRaylibColor());
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void BeginScissorMode(int x, int y, int width, int height) => Raylib6Native.BeginScissorMode(x, y, width, height);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void EndScissorMode() => Raylib6Native.EndScissorMode();
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void DrawCircle(int centerX, int centerY, float radius, Color color) => Raylib6Native.DrawCircle(centerX, centerY, radius, color.ToRaylibColor());
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void DrawFPS(int posX, int posY) => Raylib6Native.DrawFPS(posX, posY);
}
