// <auto-generated />
// Regenerate: dotnet run --project src/Novolis.Raylib.CodeGen -- generate
// ManifestSha256: e05e36aec57ce1c9bb9e85d4b1516dd3b56e34febab18adc4a37b8fbebc2f79e
#nullable enable
using Novolis.Raylib.Colors;
using Novolis.Raylib.Interop;
using Novolis.Raylib.Transformations;
using System.Runtime.CompilerServices;

namespace Novolis.Raylib.Rendering;
public static partial class Graphics
{
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void BeginDrawing() => Raylib6Native.BeginDrawing();
    public static void EndDrawing()
    {
        Raylib6Native.EndDrawing();
        RaylibDebugFrameHooks.NotifyAfterEndDrawing();
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void ClearBackground(Color color) => Raylib6Native.ClearBackground(color);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void DrawText(string text, int posX, int posY, int fontSize, Color color) => Raylib6Native.DrawText(text, posX, posY, fontSize, color);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static int MeasureText(string text, int fontSize) => Raylib6Native.MeasureText(text, fontSize);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void DrawRectangle(int posX, int posY, int width, int height, Color color) => Raylib6Native.DrawRectangle(posX, posY, width, height, color);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void DrawRectangleRec(Rectangle rec, Color color) => Raylib6Native.DrawRectangleRec(rec, color);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void DrawRectangleLines(int posX, int posY, int width, int height, Color color) => Raylib6Native.DrawRectangleLines(posX, posY, width, height, color);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void DrawLine(int startPosX, int startPosY, int endPosX, int endPosY, Color color) => Raylib6Native.DrawLine(startPosX, startPosY, endPosX, endPosY, color);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void BeginScissorMode(int x, int y, int width, int height) => Raylib6Native.BeginScissorMode(x, y, width, height);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void EndScissorMode() => Raylib6Native.EndScissorMode();
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void DrawCircle(int centerX, int centerY, float radius, Color color) => Raylib6Native.DrawCircle(centerX, centerY, radius, color);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void DrawFPS(int posX, int posY) => Raylib6Native.DrawFPS(posX, posY);
}
