// <auto-generated />
// Regenerate: dotnet run --project codegen/Novolis.Raylib.CodeGen -- generate
// ManifestSha256: 236b8c99b94d01d9e81759f998ea28215bf160148765da11922594f993fe0f28
#nullable enable
using System.Drawing;
using System.Numerics;
using Novolis.Raylib.Interop;
using System.Runtime.CompilerServices;

namespace Novolis.Raylib.Rendering;
public static partial class Textures
{
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static Texture Load(string fileName) => Texture.FromNative(Raylib6Native.LoadTexture(fileName));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void Unload(Texture texture) => Raylib6Native.UnloadTexture(texture.Native);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static bool IsValid(Texture texture) => Raylib6Native.IsTextureValid(texture.Native);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void Draw(Texture texture, int posX, int posY, Color tint) => Raylib6Native.DrawTexture(texture.Native, posX, posY, tint.ToRaylibColor());
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void DrawPro(Texture texture, RectangleF source, RectangleF dest, Vector2 origin, float rotation, Color tint) => Raylib6Native.DrawTexturePro(texture.Native, source, dest, origin, rotation, tint.ToRaylibColor());
}
