// <auto-generated />
// Regenerate: dotnet run --project src/Novolis.Raylib.CodeGen -- generate
// ManifestSha256: e05e36aec57ce1c9bb9e85d4b1516dd3b56e34febab18adc4a37b8fbebc2f79e
#nullable enable
using Novolis.Raylib.Colors;
using Novolis.Raylib.Interop;
using Novolis.Raylib.Transformations;
using System.Runtime.CompilerServices;

namespace Novolis.Raylib.Rendering;
public static partial class Textures
{
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static Texture Load(string fileName) => Texture.FromNative(Raylib6Native.LoadTexture(fileName));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void Unload(Texture texture) => Raylib6Native.UnloadTexture(texture.Native);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static bool IsValid(Texture texture) => Raylib6Native.IsTextureValid(texture.Native);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void Draw(Texture texture, int posX, int posY, Color tint) => Raylib6Native.DrawTexture(texture.Native, posX, posY, tint);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void DrawPro(Texture texture, Rectangle source, Rectangle dest, Vector2 origin, float rotation, Color tint) => Raylib6Native.DrawTexturePro(texture.Native, source, dest, origin, rotation, tint);
}
