// <auto-generated />
// Regenerate: dotnet run --project src/Novolis.Raylib.CodeGen -- generate
// ManifestSha256: e05e36aec57ce1c9bb9e85d4b1516dd3b56e34febab18adc4a37b8fbebc2f79e
#nullable enable
using Novolis.Raylib.Colors;
using Novolis.Raylib.Interop;
using Novolis.Raylib.Transformations;
using System.Runtime.CompilerServices;

namespace Novolis.Raylib.Rendering;
public static partial class World3D
{
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void Begin(Camera3D camera) => Raylib6Native.BeginMode3D(camera);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void End() => Raylib6Native.EndMode3D();
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void DrawCube(Vector3 position, float width, float height, float length, Color color) => Raylib6Native.DrawCube(position, width, height, length, color);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void DrawCubeV(Vector3 position, Vector3 size, Color color) => Raylib6Native.DrawCubeV(position, size, color);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void DrawCubeWiresV(Vector3 position, Vector3 size, Color color) => Raylib6Native.DrawCubeWiresV(position, size, color);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void DrawSphere(Vector3 centerPos, float radius, Color color) => Raylib6Native.DrawSphere(centerPos, radius, color);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void DrawSphereWires(Vector3 centerPos, float radius, int rings, int slices, Color color) => Raylib6Native.DrawSphereWires(centerPos, radius, rings, slices, color);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void DrawLine3D(Vector3 startPos, Vector3 endPos, Color color) => Raylib6Native.DrawLine3D(startPos, endPos, color);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void DrawCylinder(Vector3 position, float radiusTop, float radiusBottom, float height, int slices, Color color) => Raylib6Native.DrawCylinder(position, radiusTop, radiusBottom, height, slices, color);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void DrawGrid(int slices, float spacing) => Raylib6Native.DrawGrid(slices, spacing);
}
