// <auto-generated />
// Regenerate: dotnet run --project codegen/Novolis.Raylib.CodeGen -- generate
// ManifestSha256: 3414d24bb780080d0017c425bd7ec2e0353c54aef0598ae22f908c6d8bea1506
#nullable enable
using Novolis.Raylib.Interop;
using System.Runtime.CompilerServices;

namespace Novolis.Raylib.Audio;
/// <summary>
/// Audio device initialization.
/// </summary>
public static partial class AudioDevice
{
    /// <summary>
    /// Initialize audio device and context
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void Init() => Raylib6Native.InitAudioDevice();
    /// <summary>
    /// Close the audio device and context
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void Close() => Raylib6Native.CloseAudioDevice();
}
