// <auto-generated />
// Regenerate: dotnet run --project src/Novolis.Raylib.CodeGen -- generate
// ManifestSha256: e05e36aec57ce1c9bb9e85d4b1516dd3b56e34febab18adc4a37b8fbebc2f79e
#nullable enable
using Novolis.Raylib.Interop;
using System.Runtime.CompilerServices;

namespace Novolis.Raylib.Audio;
public static partial class AudioDevice
{
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void Init() => Raylib6Native.InitAudioDevice();
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void Close() => Raylib6Native.CloseAudioDevice();
}
