using System.Text;

namespace Novolis.Raylib.CodeGen;

internal static class FacadeEmitter
{
    public static string EmitType(FacadeTypeDefinition type, string manifestSha256)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("// Regenerate: dotnet run --project codegen/Novolis.Raylib.CodeGen -- generate");
        sb.AppendLine($"// ManifestSha256: {manifestSha256}");
        sb.AppendLine("#nullable enable");

        foreach (var u in type.Usings ?? [])
            sb.AppendLine($"using {u};");

        sb.AppendLine();
        sb.AppendLine($"namespace {type.Namespace};");
        sb.AppendLine();
        sb.AppendLine($"public static partial class {type.Name}");
        sb.AppendLine("{");

        foreach (var method in type.Methods ?? [])
        {
            if (!string.IsNullOrWhiteSpace(method.Summary))
            {
                sb.AppendLine("    /// <summary>");
                sb.AppendLine($"    /// {method.Summary}");
                sb.AppendLine("    /// </summary>");
            }

            var signature = method.Signature.Trim();
            if (!signature.Contains('('))
                throw new InvalidOperationException($"Invalid façade signature for {type.Name}.{method.Name}");

            var body = method.Body.Trim().TrimEnd(';');
            sb.AppendLine($"    public static {signature} => {body};");

            sb.AppendLine();
        }

        sb.AppendLine("}");
        return sb.ToString();
    }
}
