using System.Text;

namespace Novolis.Raylib.CodeGen;

internal static class FacadeEmitter
{
    public static string EmitType(
        FacadeTypeDefinition type,
        string manifestSha256,
        IReadOnlyDictionary<string, string> raylibComments,
        IReadOnlyDictionary<string, string> rayguiComments,
        string? facadeMethodImpl = null)
    {
        var useInlining = string.Equals(facadeMethodImpl, "AggressiveInlining", StringComparison.Ordinal);
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("// Regenerate: dotnet run --project codegen/Novolis.Raylib.CodeGen -- generate");
        sb.AppendLine($"// ManifestSha256: {manifestSha256}");
        sb.AppendLine("#nullable enable");

        foreach (var u in type.Usings ?? [])
            sb.AppendLine($"using {u};");

        if (useInlining)
            sb.AppendLine("using System.Runtime.CompilerServices;");

        sb.AppendLine();
        sb.AppendLine($"namespace {type.Namespace};");
        sb.AppendLine();

        var typeSummary = FacadeDocResolver.ResolveTypeSummary(type);
        if (!string.IsNullOrWhiteSpace(typeSummary))
        {
            sb.AppendLine("/// <summary>");
            sb.AppendLine($"/// {EscapeXml(typeSummary)}");
            sb.AppendLine("/// </summary>");
        }

        sb.AppendLine($"public static partial class {type.Name}");
        sb.AppendLine("{");

        foreach (var method in type.Methods ?? [])
        {
            var summary = FacadeDocResolver.ResolveMethodSummary(type, method, raylibComments, rayguiComments);
            sb.AppendLine("    /// <summary>");
            sb.AppendLine($"    /// {EscapeXml(summary)}");
            sb.AppendLine("    /// </summary>");

            var signature = method.Signature.Trim();
            if (!signature.Contains('('))
                throw new InvalidOperationException($"Invalid façade signature for {type.Name}.{method.Name}");

            var body = method.Body.Trim().TrimEnd(';');
            var isExpressionBody = !body.Contains('{');
            if (useInlining && isExpressionBody)
                sb.AppendLine("    [MethodImpl(MethodImplOptions.AggressiveInlining)]");

            sb.AppendLine($"    public static {signature} => {body};");
            sb.AppendLine();
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string EscapeXml(string text) =>
        text.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;");
}
