using System.Text;
using System.Text.Json;

namespace Novolis.Raylib.CodeGen;

internal static class RayguiInteropEmitter
{
    public static string Emit(string manifestPath, byte[] manifestBytes, string manifestSha256)
    {
        var json = Encoding.UTF8.GetString(manifestBytes);
        var doc = JsonSerializer.Deserialize<RayguiManifest>(json, new JsonSerializerOptions { PropertyNameCaseInsensitive = true })
                  ?? throw new InvalidOperationException($"Failed to parse {manifestPath}");
        if (doc.Functions is null || doc.Functions.Count == 0)
            throw new InvalidOperationException("Manifest has no functions.");

        var sorted = doc.Functions
            .Where(f => !string.IsNullOrEmpty(f.Export) && !string.IsNullOrEmpty(f.Template))
            .OrderBy(f => f.Export, StringComparer.Ordinal)
            .ToList();

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("// Regenerate: dotnet run --project codegen/Novolis.Raylib.CodeGen -- generate");
        sb.AppendLine($"// ManifestSha256: {manifestSha256}");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System.Runtime.InteropServices;");
        sb.AppendLine();
        sb.AppendLine("namespace Novolis.Raylib.Interop;");
        sb.AppendLine();
        sb.AppendLine("internal static unsafe partial class RayguiShimExports");
        sb.AppendLine("{");
        sb.AppendLine("    [StructLayout(LayoutKind.Sequential)]");
        sb.AppendLine("    internal struct RayguiRectangle");
        sb.AppendLine("    {");
        sb.AppendLine("        public float X;");
        sb.AppendLine("        public float Y;");
        sb.AppendLine("        public float Width;");
        sb.AppendLine("        public float Height;");
        sb.AppendLine("    }");
        sb.AppendLine();

        foreach (var fn in sorted)
        {
            var (fieldType, _) = TemplateToDelegate(fn.Template!, fn.Export!);
            sb.AppendLine($"    internal static {fieldType} {fn.Export}_ptr;");
        }

        sb.AppendLine();
        sb.AppendLine("    internal static bool TryBindShim(nint module, out string? error)");
        sb.AppendLine("    {");
        sb.AppendLine("        error = null;");
        foreach (var fn in sorted)
        {
            var (fieldType, exportName) = TemplateToDelegate(fn.Template!, fn.Export!);
            sb.AppendLine($"        var p{exportName} = NativeLibrary.GetExport(module, \"{exportName}\");");
            sb.AppendLine($"        if (p{exportName} == 0)");
            sb.AppendLine("        {");
            sb.AppendLine($"            error = \"Missing export: {exportName}\";");
            sb.AppendLine("            return false;");
            sb.AppendLine("        }");
            sb.AppendLine($"        {exportName}_ptr = ({fieldType})p{exportName};");
        }

        sb.AppendLine("        return true;");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static (string delegateType, string exportName) TemplateToDelegate(string template, string exportName) => template switch
    {
        "void_void" => ("delegate* unmanaged<void>", exportName),
        "void_float" => ("delegate* unmanaged<float, void>", exportName),
        "void_int" => ("delegate* unmanaged<int, void>", exportName),
        "int_void" => ("delegate* unmanaged<int>", exportName),
        "void_int_int_int" => ("delegate* unmanaged<int, int, int, void>", exportName),
        "int_int_int" => ("delegate* unmanaged<int, int, int>", exportName),
        "int_rect_utf8" => ("delegate* unmanaged<RayguiRectangle, byte*, int>", exportName),
        "int_rect_utf8_ptrbyte" => ("delegate* unmanaged<RayguiRectangle, byte*, byte*, int>", exportName),
        "int_rect_utf8_ptrint" => ("delegate* unmanaged<RayguiRectangle, byte*, int*, int>", exportName),
        "int_rect_utf8_utf8_ptrfloat_float_float" => ("delegate* unmanaged<RayguiRectangle, byte*, byte*, float*, float, float, int>", exportName),
        _ => throw new InvalidOperationException($"Unknown template '{template}' for {exportName}")
    };
}
