using System.Text;
using System.Text.Json;

namespace Novolis.Raylib.CodeGen;

internal static class RaylibInteropEmitter
{
    private static string Utf8Param(RaylibInteropPolicy policy) =>
        policy.UseDisableRuntimeMarshalling ? "[MarshalUsing(typeof(Utf8StringMarshaller))] " : "";

    public static string Emit(string manifestPath, byte[] manifestBytes, string manifestSha256)
    {
        var json = Encoding.UTF8.GetString(manifestBytes);
        var doc = JsonSerializer.Deserialize<RaylibManifest>(json, new JsonSerializerOptions { PropertyNameCaseInsensitive = true })
                  ?? throw new InvalidOperationException($"Failed to parse {manifestPath}");
        if (doc.Imports is null || doc.Imports.Count == 0)
            throw new InvalidOperationException("Manifest has no imports.");

        var policy = RaylibManifestModels.LoadInteropPolicy(manifestPath);
        var sortedImports = doc.Imports.OrderBy(i => i.Name, StringComparer.Ordinal).ToList();
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("// Regenerate: dotnet run --project codegen/Novolis.Raylib.CodeGen -- generate");
        sb.AppendLine($"// ManifestSha256: {manifestSha256}");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System.Runtime.InteropServices;");
        if (policy.UseDisableRuntimeMarshalling)
            sb.AppendLine("using System.Runtime.InteropServices.Marshalling;");
        sb.AppendLine("using System.Drawing;");
        sb.AppendLine("using System.Numerics;");
        sb.AppendLine("using Novolis.Raylib.Interop;");
        sb.AppendLine("using Novolis.Raylib.Rendering;");
        sb.AppendLine();
        sb.AppendLine("namespace Novolis.Raylib.Interop;");
        sb.AppendLine();

        if (doc.Structs is not null)
        {
            foreach (var st in doc.Structs.OrderBy(s => s.Name, StringComparer.Ordinal))
            {
                sb.AppendLine("/// <summary>Blittable layout for raylib C struct (generated from manifest).</summary>");
                sb.AppendLine("[StructLayout(LayoutKind.Sequential)]");
                sb.AppendLine($"internal struct {st.Name}");
                sb.AppendLine("{");
                foreach (var f in st.Fields ?? [])
                    sb.AppendLine($"    public {f.ClrType} {f.Name};");
                sb.AppendLine("}");
                sb.AppendLine();
            }
        }

        var dll = string.IsNullOrEmpty(doc.DllName) ? "raylib" : doc.DllName;
        sb.AppendLine("/// <summary>Low-level raylib 6 entry points (manifest-generated <c>[LibraryImport]</c>).</summary>");
        sb.AppendLine("internal static partial class Raylib6Native");
        sb.AppendLine("{");
        sb.AppendLine($"    private const string RaylibDll = \"{dll}\";");
        sb.AppendLine();

        foreach (var imp in sortedImports)
        {
            if (string.IsNullOrEmpty(imp.Name) || string.IsNullOrEmpty(imp.Template))
                throw new InvalidOperationException("Each import requires name and template.");
            EmitImport(sb, imp, policy);
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitImport(StringBuilder sb, RaylibImport import, RaylibInteropPolicy policy)
    {
        var name = import.Name!;
        var template = import.Template!;
        var suppress = policy.ShouldSuppressGcTransition(import);
        var utf8 = template.Contains("string_utf8", StringComparison.Ordinal);

        switch (template)
        {
            case "void_void":
                Li(sb, suppress, utf8, policy);
                sb.AppendLine($"    internal static partial void {name}();");
                sb.AppendLine();
                break;
            case "bool_void":
                Li(sb, suppress, utf8, policy);
                sb.AppendLine("    [return: MarshalAs(UnmanagedType.I1)]");
                sb.AppendLine($"    internal static partial bool {name}();");
                sb.AppendLine();
                break;
            case "int_void":
                Li(sb, suppress, utf8, policy);
                sb.AppendLine($"    internal static partial int {name}();");
                sb.AppendLine();
                break;
            case "float_void":
                Li(sb, suppress, utf8, policy);
                sb.AppendLine($"    internal static partial float {name}();");
                sb.AppendLine();
                break;
            case "void_int":
                Li(sb, suppress, utf8, policy);
                sb.AppendLine($"    internal static partial void {name}(int value);");
                sb.AppendLine();
                break;
            case "void_uint":
                Li(sb, suppress, utf8, policy);
                sb.AppendLine($"    internal static partial void {name}(uint flags);");
                sb.AppendLine();
                break;
            case "bool_int":
                Li(sb, suppress, utf8, policy);
                sb.AppendLine("    [return: MarshalAs(UnmanagedType.I1)]");
                sb.AppendLine($"    internal static partial bool {name}(int key);");
                sb.AppendLine();
                break;
            case "void_int_int_string_utf8":
                Li(sb, suppress, utf8: true, policy);
                sb.AppendLine($"    internal static partial void {name}(int width, int height, {Utf8Param(policy)}string title);");
                sb.AppendLine();
                break;
            case "void_color":
                Li(sb, suppress, utf8, policy);
                sb.AppendLine($"    internal static partial void {name}(RaylibColor color);");
                sb.AppendLine();
                break;
            case "void_string_utf8_int_int_int_color":
                Li(sb, suppress, utf8: true, policy);
                sb.AppendLine($"    internal static partial void {name}({Utf8Param(policy)}string text, int posX, int posY, int fontSize, RaylibColor color);");
                sb.AppendLine();
                break;
            case "void_int_int_int_int_color":
                Li(sb, suppress, utf8, policy);
                sb.AppendLine($"    internal static partial void {name}(int a, int b, int c, int d, RaylibColor color);");
                sb.AppendLine();
                break;
            case "void_int_int_float_color":
                Li(sb, suppress, utf8, policy);
                sb.AppendLine($"    internal static partial void {name}(int centerX, int centerY, float radius, RaylibColor color);");
                sb.AppendLine();
                break;
            case "void_int_int":
                Li(sb, suppress, utf8, policy);
                sb.AppendLine($"    internal static partial void {name}(int posX, int posY);");
                sb.AppendLine();
                break;
            case "int_string_utf8_int":
                Li(sb, suppress, utf8: true, policy);
                sb.AppendLine($"    internal static partial int {name}({Utf8Param(policy)}string text, int fontSize);");
                sb.AppendLine();
                break;
            case "void_rectangle_color":
                Li(sb, suppress, utf8, policy);
                sb.AppendLine($"    internal static partial void {name}(RectangleF rec, RaylibColor color);");
                sb.AppendLine();
                break;
            case "void_int_int_int_int":
                Li(sb, suppress, utf8, policy);
                sb.AppendLine($"    internal static partial void {name}(int x, int y, int width, int height);");
                sb.AppendLine();
                break;
            case "void_string_utf8":
                Li(sb, suppress, utf8: true, policy);
                sb.AppendLine($"    internal static partial void {name}({Utf8Param(policy)}string title);");
                sb.AppendLine();
                break;
            case "vector2_void":
                Li(sb, suppress, utf8, policy);
                sb.AppendLine($"    internal static partial Vector2 {name}();");
                sb.AppendLine();
                break;
            case "image_void":
                Li(sb, suppress, utf8, policy);
                sb.AppendLine($"    internal static partial Raylib6NativeImage {name}();");
                sb.AppendLine();
                break;
            case "void_image":
                Li(sb, suppress, utf8, policy);
                sb.AppendLine($"    internal static partial void {name}(Raylib6NativeImage image);");
                sb.AppendLine();
                break;
            case "nint_image_string_utf8_out_int":
                Li(sb, suppress, utf8: true, policy);
                sb.AppendLine($"    internal static partial nint {name}(Raylib6NativeImage image, {Utf8Param(policy)}string fileType, out int fileSize);");
                sb.AppendLine();
                break;
            case "void_nint":
                Li(sb, suppress, utf8, policy);
                sb.AppendLine($"    internal static partial void {name}(nint ptr);");
                sb.AppendLine();
                break;
            case "void_camera3d":
                Li(sb, suppress, utf8, policy);
                sb.AppendLine($"    internal static partial void {name}(Camera3D camera);");
                sb.AppendLine();
                break;
            case "void_vector3_float_float_float_color":
                Li(sb, suppress, utf8, policy);
                sb.AppendLine($"    internal static partial void {name}(Vector3 position, float width, float height, float length, RaylibColor color);");
                sb.AppendLine();
                break;
            case "void_vector3_vector3_color":
                Li(sb, suppress, utf8, policy);
                sb.AppendLine($"    internal static partial void {name}(Vector3 startPos, Vector3 endPos, RaylibColor color);");
                sb.AppendLine();
                break;
            case "void_vector3_float_color":
                Li(sb, suppress, utf8, policy);
                sb.AppendLine($"    internal static partial void {name}(Vector3 centerPos, float radius, RaylibColor color);");
                sb.AppendLine();
                break;
            case "void_vector3_float_int_int_color":
                Li(sb, suppress, utf8, policy);
                sb.AppendLine($"    internal static partial void {name}(Vector3 centerPos, float radius, int rings, int slices, RaylibColor color);");
                sb.AppendLine();
                break;
            case "void_vector3_float_float_float_int_color":
                Li(sb, suppress, utf8, policy);
                sb.AppendLine($"    internal static partial void {name}(Vector3 position, float radiusTop, float radiusBottom, float height, int slices, RaylibColor color);");
                sb.AppendLine();
                break;
            case "void_int_float":
                Li(sb, suppress, utf8, policy);
                sb.AppendLine($"    internal static partial void {name}(int slices, float spacing);");
                sb.AppendLine();
                break;
            case "texture_string_utf8":
                Li(sb, suppress, utf8: true, policy);
                sb.AppendLine($"    internal static partial Raylib6NativeTexture {name}({Utf8Param(policy)}string fileName);");
                sb.AppendLine();
                break;
            case "void_texture":
                Li(sb, suppress, utf8, policy);
                sb.AppendLine($"    internal static partial void {name}(Raylib6NativeTexture texture);");
                sb.AppendLine();
                break;
            case "bool_texture":
                Li(sb, suppress, utf8, policy);
                sb.AppendLine("    [return: MarshalAs(UnmanagedType.I1)]");
                sb.AppendLine($"    internal static partial bool {name}(Raylib6NativeTexture texture);");
                sb.AppendLine();
                break;
            case "void_texture_int_int_color":
                Li(sb, suppress, utf8, policy);
                sb.AppendLine($"    internal static partial void {name}(Raylib6NativeTexture texture, int posX, int posY, RaylibColor tint);");
                sb.AppendLine();
                break;
            case "void_texture_rectangle_rectangle_vector2_float_color":
                Li(sb, suppress, utf8, policy);
                sb.AppendLine($"    internal static partial void {name}(Raylib6NativeTexture texture, RectangleF source, RectangleF dest, Vector2 origin, float rotation, RaylibColor tint);");
                sb.AppendLine();
                break;
            default:
                throw new InvalidOperationException($"Unknown template '{template}' for import '{name}'.");
        }
    }

    private static void Li(StringBuilder sb, bool suppressGcTransition, bool utf8, RaylibInteropPolicy policy)
    {
        if (utf8)
            LiUtf8(sb, suppressGcTransition, policy);
        else
            LiBlittable(sb, suppressGcTransition, policy);
    }

    private static void LiBlittable(StringBuilder sb, bool suppressGcTransition, RaylibInteropPolicy policy)
    {
        if (suppressGcTransition && !policy.UseDisableRuntimeMarshalling)
            sb.AppendLine("    [LibraryImport(RaylibDll, SuppressGCTransition = true)]");
        else
            sb.AppendLine("    [LibraryImport(RaylibDll)]");
    }

    private static void LiUtf8(StringBuilder sb, bool suppressGcTransition, RaylibInteropPolicy policy)
    {
        if (policy.UseDisableRuntimeMarshalling)
            LiBlittable(sb, suppressGcTransition, policy);
        else if (suppressGcTransition)
            sb.AppendLine("    [LibraryImport(RaylibDll, StringMarshalling = StringMarshalling.Utf8, SuppressGCTransition = true)]");
        else
            sb.AppendLine("    [LibraryImport(RaylibDll, StringMarshalling = StringMarshalling.Utf8)]");
    }
}
