using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Novolis.Raylib.CodeGen;

internal static class RaylibDebugHooksEmitter
{
    public static string Emit(string manifestPath, byte[] manifestBytes, string manifestSha256)
    {
        var json = Encoding.UTF8.GetString(manifestBytes);
        var doc = JsonSerializer.Deserialize<DebugManifest>(json, new JsonSerializerOptions { PropertyNameCaseInsensitive = true })
                  ?? throw new InvalidOperationException($"Failed to parse {manifestPath}");
        if (doc.Symbols is null)
            throw new InvalidOperationException("Manifest missing symbols.");

        var s = doc.Symbols;
        if (string.IsNullOrEmpty(s.LoadImageFromScreen) || string.IsNullOrEmpty(s.ExportImageToMemory) ||
            string.IsNullOrEmpty(s.UnloadImage) || string.IsNullOrEmpty(s.MemFree))
        {
            throw new InvalidOperationException(
                "Manifest symbols.loadImageFromScreen, exportImageToMemory, unloadImage, memFree are required.");
        }

        var envVar = string.IsNullOrWhiteSpace(doc.CaptureEnvVar) ? "NOVOLIS_RAYLIB_DEBUG_CAPTURE" : doc.CaptureEnvVar!;
        var pngType = string.IsNullOrWhiteSpace(doc.CapturePngFileType) ? ".png" : doc.CapturePngFileType!;
        var notify = doc.NotifyAfterNativeCall;
        var load = s.LoadImageFromScreen;
        var export = s.ExportImageToMemory;
        var unload = s.UnloadImage;
        var memFree = s.MemFree;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("// Regenerate: dotnet run --project src/Novolis.Raylib.CodeGen -- generate");
        sb.AppendLine($"// ManifestSha256: {manifestSha256}");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System.Runtime.InteropServices;");
        sb.AppendLine("using Novolis.Raylib.Debug;");
        sb.AppendLine();
        sb.AppendLine("namespace Novolis.Raylib.Interop;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>Debug-only hooks for automation / diagnostics. Native calls use manifest-defined <see cref=\"Raylib6Native\"/> entry points.</summary>");
        sb.AppendLine("internal static partial class RaylibDebugFrameHooks");
        sb.AppendLine("{");
        sb.AppendLine($"    internal const string CaptureEnvironmentVariable = \"{EscapeCSharpString(envVar)}\";");
        sb.AppendLine();
        sb.AppendLine("#if DEBUG");
        sb.AppendLine($"    /// <summary>Invoked on the render thread immediately after <see cref=\"Raylib6Native.{notify}\"/> from façade code.</summary>");
        sb.AppendLine($"    public static event Action? After{notify};");
        sb.AppendLine("#endif");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Notify subscribers after the native call named in raylib-debug.manifest.json (<c>notifyAfterNativeCall</c>).</summary>");
        sb.AppendLine($"    internal static void NotifyAfter{notify}()");
        sb.AppendLine("    {");
        sb.AppendLine("#if DEBUG");
        sb.AppendLine($"        After{notify}?.Invoke();");
        sb.AppendLine("#endif");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("#if DEBUG");
        sb.AppendLine($"    /// <summary>When <see cref=\"RaylibDebug.MemoryFramebufferCaptureEnabled\"/> is set or <see cref=\"CaptureEnvironmentVariable\"/> is <c>1</c>/<c>true</c>/<c>yes</c>, captures the framebuffer to PNG bytes in memory (raylib <c>{load}</c> / <c>{export}</c>).</summary>");
        sb.AppendLine("    internal static bool TryCaptureFramePng([System.Diagnostics.CodeAnalysis.NotNullWhen(true)] out byte[]? png)");
        sb.AppendLine("    {");
        sb.AppendLine("        png = null;");
        sb.AppendLine("        if (!RaylibDebug.IsMemoryFramebufferCaptureRequested())");
        sb.AppendLine("            return false;");
        sb.AppendLine();
        sb.AppendLine($"        var image = Raylib6Native.{load}();");
        sb.AppendLine("        try");
        sb.AppendLine("        {");
        sb.AppendLine($"            var ptr = Raylib6Native.{export}(image, \"{EscapeCSharpString(pngType)}\", out var size);");
        sb.AppendLine("            if (ptr == 0 || size <= 0)");
        sb.AppendLine("                return false;");
        sb.AppendLine("            png = new byte[size];");
        sb.AppendLine("            Marshal.Copy(ptr, png, 0, size);");
        sb.AppendLine($"            Raylib6Native.{memFree}(ptr);");
        sb.AppendLine("            return true;");
        sb.AppendLine("        }");
        sb.AppendLine("        finally");
        sb.AppendLine("        {");
        sb.AppendLine($"            Raylib6Native.{unload}(image);");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("#else");
        sb.AppendLine("    internal static bool TryCaptureFramePng(out byte[]? png)");
        sb.AppendLine("    {");
        sb.AppendLine("        png = null;");
        sb.AppendLine("        return false;");
        sb.AppendLine("    }");
        sb.AppendLine("#endif");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string EscapeCSharpString(string s) => s.Replace("\\", "\\\\").Replace("\"", "\\\"");
}

internal sealed class DebugManifest
{
    [JsonPropertyName("notifyAfterNativeCall")]
    public string NotifyAfterNativeCall { get; set; } = "EndDrawing";

    [JsonPropertyName("captureEnvVar")]
    public string? CaptureEnvVar { get; set; }

    [JsonPropertyName("capturePngFileType")]
    public string? CapturePngFileType { get; set; }

    [JsonPropertyName("symbols")]
    public SymbolMap? Symbols { get; set; }
}

internal sealed class SymbolMap
{
    [JsonPropertyName("loadImageFromScreen")]
    public string? LoadImageFromScreen { get; set; }

    [JsonPropertyName("exportImageToMemory")]
    public string? ExportImageToMemory { get; set; }

    [JsonPropertyName("unloadImage")]
    public string? UnloadImage { get; set; }

    [JsonPropertyName("memFree")]
    public string? MemFree { get; set; }
}
