// DEPRECATED: use dotnet run --project tools/Novolis.Raylib.CodeGen -- generate
// Legacy file-based emitter kept for reference; run.cs no longer invokes this script.
// Emit Raylib6Native.g.cs from raylib-exports.manifest.json (deterministic: sorted imports, fixed layout).
// Usage (repo root): dotnet run tools/raylib6-pipeline/generate-raylib-interop.cs
#:sdk Microsoft.NET.Sdk
#:property TargetFramework=net10.0
#:property PublishAot=false
#:property PackAsTool=false
#:property ImplicitUsings=enable
#:property Nullable=enable
#:property ManagePackageVersionsCentrally=false

using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;

if (args is ["-h"] or ["--help"])
{
	Console.WriteLine("""
		generate-raylib-interop — reads tools/raylib6-pipeline/raylib-exports.manifest.json
		and writes src/StarConflictsRevolt.Raylib6.Bindings/Interop/Raylib6Native.g.cs
		""");
	return 0;
}

var repoRoot = FindRepoRoot();
var manifestPath = Path.Combine(repoRoot, "tools", "raylib6-pipeline", "raylib-exports.manifest.json");
var outPath = Path.Combine(repoRoot, "src", "StarConflictsRevolt.Raylib6.Bindings", "Interop", "Raylib6Native.g.cs");
if (!File.Exists(manifestPath))
{
	Console.Error.WriteLine($"Missing manifest: {manifestPath}");
	return 2;
}

var jsonBytes = File.ReadAllBytes(manifestPath);
var json = Encoding.UTF8.GetString(jsonBytes);
var doc = JsonSerializer.Deserialize<RaylibManifest>(json, new JsonSerializerOptions { PropertyNameCaseInsensitive = true });
if (doc?.Imports is null || doc.Imports.Count == 0)
{
	Console.Error.WriteLine("Manifest has no imports.");
	return 3;
}

var manifestSha256 = Convert.ToHexString(SHA256.HashData(jsonBytes)).ToLowerInvariant();
var sortedImports = doc.Imports.OrderBy(i => i.Name, StringComparer.Ordinal).ToList();

var sb = new StringBuilder();
sb.AppendLine("// <auto-generated />");
sb.AppendLine("// Regenerate: dotnet run tools/raylib6-pipeline/generate-raylib-interop.cs");
sb.AppendLine($"// ManifestSha256: {manifestSha256}");
sb.AppendLine("#nullable enable");
sb.AppendLine("using System.Runtime.InteropServices;");
sb.AppendLine("using StarConflictsRevolt.Raylib.Colors;");
sb.AppendLine("using StarConflictsRevolt.Raylib.Transformations;");
sb.AppendLine();
sb.AppendLine("namespace StarConflictsRevolt.Raylib.Interop;");
sb.AppendLine();

if (doc.Structs is not null)
{
	foreach (var st in doc.Structs.OrderBy(s => s.Name, StringComparer.Ordinal))
	{
		sb.AppendLine("/// <summary>Blittable layout for raylib C struct (generated from manifest).</summary>");
		sb.AppendLine("[StructLayout(LayoutKind.Sequential)]");
		sb.AppendLine($"internal struct {st.Name}");
		sb.AppendLine("{");
		foreach (var f in st.Fields ?? [])
			sb.AppendLine($"    public {f.ClrType} {f.Name};");
		sb.AppendLine("}");
		sb.AppendLine();
	}
}

var dll = string.IsNullOrEmpty(doc.DllName) ? "raylib" : doc.DllName;
sb.AppendLine("/// <summary>Low-level raylib 6 entry points (manifest-generated <c>[LibraryImport]</c>).</summary>");
sb.AppendLine("internal static partial class Raylib6Native");
sb.AppendLine("{");
sb.AppendLine($"    private const string RaylibDll = \"{dll}\";");
sb.AppendLine();

foreach (var imp in sortedImports)
{
	if (string.IsNullOrEmpty(imp.Name) || string.IsNullOrEmpty(imp.Template))
		throw new InvalidOperationException("Each import requires name and template.");

	EmitImport(sb, imp.Name, imp.Template);
}

sb.AppendLine("}");

Directory.CreateDirectory(Path.GetDirectoryName(outPath)!);
File.WriteAllText(outPath, sb.ToString(), new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
Console.WriteLine($"Wrote {sortedImports.Count} imports to {outPath}");
return 0;

static void EmitImport(StringBuilder sb, string name, string template)
{
	switch (template)
	{
		case "void_void":
			Li(sb, "RaylibDll");
			sb.AppendLine($"    internal static partial void {name}();");
			sb.AppendLine();
			break;
		case "bool_void":
			Li(sb, "RaylibDll");
			sb.AppendLine("    [return: MarshalAs(UnmanagedType.I1)]");
			sb.AppendLine($"    internal static partial bool {name}();");
			sb.AppendLine();
			break;
		case "int_void":
			Li(sb, "RaylibDll");
			sb.AppendLine($"    internal static partial int {name}();");
			sb.AppendLine();
			break;
		case "float_void":
			Li(sb, "RaylibDll");
			sb.AppendLine($"    internal static partial float {name}();");
			sb.AppendLine();
			break;
		case "void_int":
			Li(sb, "RaylibDll");
			sb.AppendLine($"    internal static partial void {name}(int value);");
			sb.AppendLine();
			break;
		case "void_uint":
			Li(sb, "RaylibDll");
			sb.AppendLine($"    internal static partial void {name}(uint flags);");
			sb.AppendLine();
			break;
		case "bool_int":
			Li(sb, "RaylibDll");
			sb.AppendLine("    [return: MarshalAs(UnmanagedType.I1)]");
			sb.AppendLine($"    internal static partial bool {name}(int key);");
			sb.AppendLine();
			break;
		case "void_int_int_string_utf8":
			LiUtf8(sb, "RaylibDll");
			sb.AppendLine($"    internal static partial void {name}(int width, int height, string title);");
			sb.AppendLine();
			break;
		case "void_color":
			Li(sb, "RaylibDll");
			sb.AppendLine($"    internal static partial void {name}(Color color);");
			sb.AppendLine();
			break;
		case "void_string_utf8_int_int_int_color":
			LiUtf8(sb, "RaylibDll");
			sb.AppendLine($"    internal static partial void {name}(string text, int posX, int posY, int fontSize, Color color);");
			sb.AppendLine();
			break;
		case "void_int_int_int_int_color":
			Li(sb, "RaylibDll");
			sb.AppendLine($"    internal static partial void {name}(int a, int b, int c, int d, Color color);");
			sb.AppendLine();
			break;
		case "void_int_int_float_color":
			Li(sb, "RaylibDll");
			sb.AppendLine($"    internal static partial void {name}(int centerX, int centerY, float radius, Color color);");
			sb.AppendLine();
			break;
		case "void_int_int":
			Li(sb, "RaylibDll");
			sb.AppendLine($"    internal static partial void {name}(int posX, int posY);");
			sb.AppendLine();
			break;
		case "int_string_utf8_int":
			LiUtf8(sb, "RaylibDll");
			sb.AppendLine($"    internal static partial int {name}(string text, int fontSize);");
			sb.AppendLine();
			break;
		case "void_rectangle_color":
			Li(sb, "RaylibDll");
			sb.AppendLine($"    internal static partial void {name}(Rectangle rec, Color color);");
			sb.AppendLine();
			break;
		case "void_int_int_int_int":
			Li(sb, "RaylibDll");
			sb.AppendLine($"    internal static partial void {name}(int x, int y, int width, int height);");
			sb.AppendLine();
			break;
		case "void_string_utf8":
			LiUtf8(sb, "RaylibDll");
			sb.AppendLine($"    internal static partial void {name}(string title);");
			sb.AppendLine();
			break;
		case "vector2_void":
			Li(sb, "RaylibDll");
			sb.AppendLine($"    internal static partial Vector2 {name}();");
			sb.AppendLine();
			break;
		case "image_void":
			Li(sb, "RaylibDll");
			sb.AppendLine($"    internal static partial Raylib6NativeImage {name}();");
			sb.AppendLine();
			break;
		case "void_image":
			Li(sb, "RaylibDll");
			sb.AppendLine($"    internal static partial void {name}(Raylib6NativeImage image);");
			sb.AppendLine();
			break;
		case "nint_image_string_utf8_out_int":
			LiUtf8(sb, "RaylibDll");
			sb.AppendLine($"    internal static partial nint {name}(Raylib6NativeImage image, string fileType, out int fileSize);");
			sb.AppendLine();
			break;
		case "void_nint":
			Li(sb, "RaylibDll");
			sb.AppendLine($"    internal static partial void {name}(nint ptr);");
			sb.AppendLine();
			break;
		default:
			throw new InvalidOperationException($"Unknown template '{template}' for import '{name}'.");
	}
}

static void Li(StringBuilder sb, string dllConst) =>
	sb.AppendLine($"    [LibraryImport({dllConst})]");

static void LiUtf8(StringBuilder sb, string dllConst) =>
	sb.AppendLine($"    [LibraryImport({dllConst}, StringMarshalling = StringMarshalling.Utf8)]");

static string FindRepoRoot()
{
	var dir = new DirectoryInfo(AppContext.BaseDirectory);
	while (dir is not null)
	{
		if (File.Exists(Path.Combine(dir.FullName, "Directory.Packages.props")))
			return dir.FullName;
		dir = dir.Parent;
	}

	return Directory.GetCurrentDirectory();
}

internal sealed class RaylibManifest
{
	[JsonPropertyName("dllName")]
	public string? DllName { get; set; }

	[JsonPropertyName("structs")]
	public List<RaylibStruct>? Structs { get; set; }

	[JsonPropertyName("imports")]
	public List<RaylibImport>? Imports { get; set; }
}

internal sealed class RaylibStruct
{
	[JsonPropertyName("name")]
	public string? Name { get; set; }

	[JsonPropertyName("fields")]
	public List<RaylibField>? Fields { get; set; }
}

internal sealed class RaylibField
{
	[JsonPropertyName("name")]
	public string? Name { get; set; }

	[JsonPropertyName("clrType")]
	public string? ClrType { get; set; }
}

internal sealed class RaylibImport
{
	[JsonPropertyName("name")]
	public string? Name { get; set; }

	[JsonPropertyName("template")]
	public string? Template { get; set; }
}
