// DEPRECATED: use dotnet run --project tools/Novolis.Raylib.CodeGen -- generate
// Legacy file-based emitter; run.cs no longer invokes this script.
// Emit RaylibDebugFrameHooks.g.cs from raylib-debug.manifest.json (references Raylib6Native symbol names).
// Usage (repo root): dotnet run tools/raylib6-pipeline/generate-raylib-debug-hooks.cs
#:sdk Microsoft.NET.Sdk
#:property TargetFramework=net10.0
#:property PublishAot=false
#:property PackAsTool=false
#:property ImplicitUsings=enable
#:property Nullable=enable
#:property ManagePackageVersionsCentrally=false

using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;

if (args is ["-h"] or ["--help"])
{
	Console.WriteLine("""
		generate-raylib-debug-hooks — reads tools/raylib6-pipeline/raylib-debug.manifest.json
		and writes src/StarConflictsRevolt.Raylib6.Bindings/Interop/RaylibDebugFrameHooks.g.cs
		""");
	return 0;
}

var repoRoot = FindRepoRoot();
var manifestPath = Path.Combine(repoRoot, "tools", "raylib6-pipeline", "raylib-debug.manifest.json");
var outPath = Path.Combine(repoRoot, "src", "StarConflictsRevolt.Raylib6.Bindings", "Interop", "RaylibDebugFrameHooks.g.cs");
if (!File.Exists(manifestPath))
{
	Console.Error.WriteLine($"Missing manifest: {manifestPath}");
	return 2;
}

var jsonBytes = File.ReadAllBytes(manifestPath);
var json = Encoding.UTF8.GetString(jsonBytes);
var doc = JsonSerializer.Deserialize<DebugManifest>(json, new JsonSerializerOptions { PropertyNameCaseInsensitive = true });
if (doc?.Symbols is null)
{
	Console.Error.WriteLine("Manifest missing symbols.");
	return 3;
}

var s = doc.Symbols;
if (string.IsNullOrEmpty(s.LoadImageFromScreen) || string.IsNullOrEmpty(s.ExportImageToMemory) ||
    string.IsNullOrEmpty(s.UnloadImage) || string.IsNullOrEmpty(s.MemFree))
{
	Console.Error.WriteLine("Manifest symbols.loadImageFromScreen, exportImageToMemory, unloadImage, memFree are required.");
	return 4;
}

var manifestSha256 = Convert.ToHexString(SHA256.HashData(jsonBytes)).ToLowerInvariant();
var envVar = string.IsNullOrWhiteSpace(doc.CaptureEnvVar) ? "NOVOLIS_RAYLIB_DEBUG_CAPTURE" : doc.CaptureEnvVar!;
var pngType = string.IsNullOrWhiteSpace(doc.CapturePngFileType) ? ".png" : doc.CapturePngFileType!;

var load = s.LoadImageFromScreen;
var export = s.ExportImageToMemory;
var unload = s.UnloadImage;
var memFree = s.MemFree;

var sb = new StringBuilder();
sb.AppendLine("// <auto-generated />");
sb.AppendLine("// Regenerate: dotnet run tools/raylib6-pipeline/generate-raylib-debug-hooks.cs");
sb.AppendLine($"// ManifestSha256: {manifestSha256}");
sb.AppendLine("#nullable enable");
sb.AppendLine("using System.Runtime.InteropServices;");
sb.AppendLine("using StarConflictsRevolt.Raylib.Debug;");
sb.AppendLine();
sb.AppendLine("namespace StarConflictsRevolt.Raylib.Interop;");
sb.AppendLine();
sb.AppendLine("/// <summary>Debug-only hooks for automation / diagnostics. Native calls use manifest-defined <see cref=\"Raylib6Native\"/> entry points.</summary>");
sb.AppendLine("internal static partial class RaylibDebugFrameHooks");
sb.AppendLine("{");
sb.AppendLine($"    internal const string CaptureEnvironmentVariable = \"{EscapeCSharpString(envVar)}\";");
sb.AppendLine();
sb.AppendLine("#if DEBUG");
sb.AppendLine("    /// <summary>Invoked on the render thread immediately after <see cref=\"Raylib6Native." + doc.NotifyAfterNativeCall + "\"/> from façade code.</summary>");
sb.AppendLine("    public static event Action? After" + doc.NotifyAfterNativeCall + ";");
sb.AppendLine("#endif");
sb.AppendLine();
sb.AppendLine("    /// <summary>Notify subscribers after the native call named in raylib-debug.manifest.json (<c>notifyAfterNativeCall</c>).</summary>");
sb.AppendLine("    internal static void NotifyAfter" + doc.NotifyAfterNativeCall + "()");
sb.AppendLine("    {");
sb.AppendLine("#if DEBUG");
sb.AppendLine("        After" + doc.NotifyAfterNativeCall + "?.Invoke();");
sb.AppendLine("#endif");
sb.AppendLine("    }");
sb.AppendLine();
sb.AppendLine("#if DEBUG");
sb.AppendLine("    /// <summary>When <see cref=\"RaylibDebug.MemoryFramebufferCaptureEnabled\"/> is set or <see cref=\"CaptureEnvironmentVariable\"/> is <c>1</c>/<c>true</c>/<c>yes</c>, captures the framebuffer to PNG bytes in memory (raylib <c>" + load + "</c> / <c>" + export + "</c>).</summary>");
sb.AppendLine("    internal static bool TryCaptureFramePng([System.Diagnostics.CodeAnalysis.NotNullWhen(true)] out byte[]? png)");
sb.AppendLine("    {");
sb.AppendLine("        png = null;");
sb.AppendLine("        if (!RaylibDebug.IsMemoryFramebufferCaptureRequested())");
sb.AppendLine("            return false;");
sb.AppendLine();
sb.AppendLine($"        var image = Raylib6Native.{load}();");
sb.AppendLine($"        try");
sb.AppendLine("        {");
sb.AppendLine($"            var ptr = Raylib6Native.{export}(image, \"{EscapeCSharpString(pngType)}\", out var size);");
sb.AppendLine("            if (ptr == 0 || size <= 0)");
sb.AppendLine("                return false;");
sb.AppendLine("            png = new byte[size];");
sb.AppendLine("            Marshal.Copy(ptr, png, 0, size);");
sb.AppendLine($"            Raylib6Native.{memFree}(ptr);");
sb.AppendLine("            return true;");
sb.AppendLine("        }");
sb.AppendLine("        finally");
sb.AppendLine("        {");
sb.AppendLine($"            Raylib6Native.{unload}(image);");
sb.AppendLine("        }");
sb.AppendLine("    }");
sb.AppendLine();
sb.AppendLine("#else");
sb.AppendLine("    internal static bool TryCaptureFramePng(out byte[]? png)");
sb.AppendLine("    {");
sb.AppendLine("        png = null;");
sb.AppendLine("        return false;");
sb.AppendLine("    }");
sb.AppendLine("#endif");
sb.AppendLine("}");

Directory.CreateDirectory(Path.GetDirectoryName(outPath)!);
File.WriteAllText(outPath, sb.ToString(), new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
Console.WriteLine($"Wrote {outPath}");
return 0;

static string EscapeCSharpString(string s) => s.Replace("\\", "\\\\").Replace("\"", "\\\"");

static string FindRepoRoot()
{
	var dir = new DirectoryInfo(AppContext.BaseDirectory);
	while (dir is not null)
	{
		if (File.Exists(Path.Combine(dir.FullName, "Directory.Packages.props")))
			return dir.FullName;
		dir = dir.Parent;
	}

	return Directory.GetCurrentDirectory();
}

internal sealed class DebugManifest
{
	[JsonPropertyName("notifyAfterNativeCall")]
	public string NotifyAfterNativeCall { get; set; } = "EndDrawing";

	[JsonPropertyName("captureEnvVar")]
	public string? CaptureEnvVar { get; set; }

	[JsonPropertyName("capturePngFileType")]
	public string? CapturePngFileType { get; set; }

	[JsonPropertyName("symbols")]
	public SymbolMap? Symbols { get; set; }
}

internal sealed class SymbolMap
{
	[JsonPropertyName("loadImageFromScreen")]
	public string? LoadImageFromScreen { get; set; }

	[JsonPropertyName("exportImageToMemory")]
	public string? ExportImageToMemory { get; set; }

	[JsonPropertyName("unloadImage")]
	public string? UnloadImage { get; set; }

	[JsonPropertyName("memFree")]
	public string? MemFree { get; set; }
}
