// DEPRECATED: use dotnet run --project tools/Novolis.Raylib.CodeGen -- generate
// Legacy file-based emitter; run.cs no longer invokes this script.
// Emit RayguiShimExports.g.cs from raygui-exports.manifest.json (deterministic: sorted exports, fixed layout).
// Usage (repo root): dotnet run tools/raylib6-pipeline/generate-raygui-interop.cs
#:sdk Microsoft.NET.Sdk
#:property TargetFramework=net10.0
#:property PublishAot=false
#:property PackAsTool=false
#:property ImplicitUsings=enable
#:property Nullable=enable
#:property ManagePackageVersionsCentrally=false

using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;

if (args is ["-h"] or ["--help"])
{
	Console.WriteLine("""
		generate-raygui-interop — reads tools/raylib6-pipeline/raygui-exports.manifest.json
		and writes src/StarConflictsRevolt.Raylib6.Bindings/Interop/RayguiShimExports.g.cs
		""");
	return 0;
}

var repoRoot = FindRepoRoot();
var manifestPath = Path.Combine(repoRoot, "tools", "raylib6-pipeline", "raygui-exports.manifest.json");
var outPath = Path.Combine(repoRoot, "src", "StarConflictsRevolt.Raylib6.Bindings", "Interop", "RayguiShimExports.g.cs");
if (!File.Exists(manifestPath))
{
	Console.Error.WriteLine($"Missing manifest: {manifestPath}");
	return 2;
}

var jsonBytes = File.ReadAllBytes(manifestPath);
var json = Encoding.UTF8.GetString(jsonBytes);
var doc = JsonSerializer.Deserialize<Manifest>(json, new JsonSerializerOptions { PropertyNameCaseInsensitive = true });
if (doc?.Functions is null || doc.Functions.Count == 0)
{
	Console.Error.WriteLine("Manifest has no functions.");
	return 3;
}

var manifestSha256 = Convert.ToHexString(SHA256.HashData(jsonBytes)).ToLowerInvariant();
var sorted = doc.Functions
	.Where(f => !string.IsNullOrEmpty(f.Export) && !string.IsNullOrEmpty(f.Template))
	.OrderBy(f => f.Export, StringComparer.Ordinal)
	.ToList();

var sb = new StringBuilder();
sb.AppendLine("// <auto-generated />");
sb.AppendLine("// Regenerate: dotnet run tools/raylib6-pipeline/generate-raygui-interop.cs");
sb.AppendLine($"// ManifestSha256: {manifestSha256}");
sb.AppendLine("#nullable enable");
sb.AppendLine("using System.Runtime.InteropServices;");
sb.AppendLine();
sb.AppendLine("namespace StarConflictsRevolt.Raylib.Interop;");
sb.AppendLine();
sb.AppendLine("internal static unsafe partial class RayguiShimExports");
sb.AppendLine("{");
sb.AppendLine("    [StructLayout(LayoutKind.Sequential)]");
sb.AppendLine("    internal struct RayguiRectangle");
sb.AppendLine("    {");
sb.AppendLine("        public float X;");
sb.AppendLine("        public float Y;");
sb.AppendLine("        public float Width;");
sb.AppendLine("        public float Height;");
sb.AppendLine("    }");
sb.AppendLine();

foreach (var fn in sorted)
{
	var (fieldType, _) = TemplateToDelegate(fn.Template!, fn.Export!);
	sb.AppendLine($"    internal static {fieldType} {fn.Export}_ptr;");
}

sb.AppendLine();
sb.AppendLine("    internal static bool TryBindShim(nint module, out string? error)");
sb.AppendLine("    {");
sb.AppendLine("        error = null;");
foreach (var fn in sorted)
{
	var (fieldType, exportName) = TemplateToDelegate(fn.Template!, fn.Export!);
	sb.AppendLine($"        var p{exportName} = NativeLibrary.GetExport(module, \"{exportName}\");");
	sb.AppendLine($"        if (p{exportName} == 0)");
	sb.AppendLine("        {");
	sb.AppendLine($"            error = \"Missing export: {exportName}\";");
	sb.AppendLine("            return false;");
	sb.AppendLine("        }");
	sb.AppendLine($"        {exportName}_ptr = ({fieldType})p{exportName};");
}

sb.AppendLine("        return true;");
sb.AppendLine("    }");
sb.AppendLine("}");

Directory.CreateDirectory(Path.GetDirectoryName(outPath)!);
File.WriteAllText(outPath, sb.ToString(), new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
Console.WriteLine($"Wrote {sorted.Count} exports to {outPath}");
return 0;

static (string delegateType, string exportName) TemplateToDelegate(string template, string exportName) => template switch
{
	"void_void" => ("delegate* unmanaged<void>", exportName),
	"void_float" => ("delegate* unmanaged<float, void>", exportName),
	"void_int" => ("delegate* unmanaged<int, void>", exportName),
	"int_void" => ("delegate* unmanaged<int>", exportName),
	"void_int_int_int" => ("delegate* unmanaged<int, int, int, void>", exportName),
	"int_int_int" => ("delegate* unmanaged<int, int, int>", exportName),
	"int_rect_utf8" => ("delegate* unmanaged<RayguiRectangle, byte*, int>", exportName),
	"int_rect_utf8_ptrbyte" => ("delegate* unmanaged<RayguiRectangle, byte*, byte*, int>", exportName),
	"int_rect_utf8_ptrint" => ("delegate* unmanaged<RayguiRectangle, byte*, int*, int>", exportName),
	"int_rect_utf8_utf8_ptrfloat_float_float" => ("delegate* unmanaged<RayguiRectangle, byte*, byte*, float*, float, float, int>", exportName),
	_ => throw new InvalidOperationException($"Unknown template '{template}' for {exportName}")
};

static string FindRepoRoot()
{
	var dir = new DirectoryInfo(AppContext.BaseDirectory);
	while (dir is not null)
	{
		if (File.Exists(Path.Combine(dir.FullName, "Directory.Packages.props")))
			return dir.FullName;
		dir = dir.Parent;
	}

	return Directory.GetCurrentDirectory();
}

internal sealed class Manifest
{
	[JsonPropertyName("functions")]
	public List<ManifestFn>? Functions { get; set; }
}

internal sealed class ManifestFn
{
	public string? Export { get; set; }
	public string? Template { get; set; }
}
