// <auto-generated />
// Regenerate: dotnet run --project src/Novolis.Raylib.CodeGen -- generate
// ManifestSha256: e05e36aec57ce1c9bb9e85d4b1516dd3b56e34febab18adc4a37b8fbebc2f79e
#nullable enable
using Novolis.Raylib.Interop;
using System.Runtime.CompilerServices;

namespace Novolis.Raylib.Timing;
public static partial class Time
{
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void SetTargetFPS(int fps) => Raylib6Native.SetTargetFPS(fps);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static float GetFrameTime() => Raylib6Native.GetFrameTime();
}
