// <auto-generated />
// Regenerate: dotnet run --project codegen/Novolis.Raylib.CodeGen -- generate
// ManifestSha256: 3414d24bb780080d0017c425bd7ec2e0353c54aef0598ae22f908c6d8bea1506
#nullable enable
using Novolis.Raylib.Interop;
using System.Runtime.CompilerServices;

namespace Novolis.Raylib.Timing;
/// <summary>
/// Frame timing and target FPS.
/// </summary>
public static partial class Time
{
    /// <summary>
    /// Set target FPS (maximum)
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void SetTargetFPS(int fps) => Raylib6Native.SetTargetFPS(fps);
    /// <summary>
    /// Get time in seconds for last frame drawn (delta time)
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static float GetFrameTime() => Raylib6Native.GetFrameTime();
}
