// <auto-generated />
// Regenerate: dotnet run --project codegen/Novolis.Raylib.CodeGen -- generate
// ManifestSha256: c5e666aec25c3034bc5d2639dfce85ebd4bbda7b7c587047807104cb5129bf3b
#nullable enable
using Novolis.Raylib.Interop;
using System.Runtime.CompilerServices;

namespace Novolis.Raylib.Timing;
public static partial class Time
{
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void SetTargetFPS(int fps) => Raylib6Native.SetTargetFPS(fps);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static float GetFrameTime() => Raylib6Native.GetFrameTime();
}
