// <auto-generated />
// Regenerate: dotnet run --project codegen/Novolis.Raylib.CodeGen -- generate
// ManifestSha256: f8bb4e7b3d9d268f94331ce314658aea9d9025fbd2444b30e13564c549e91865
#nullable enable
using System.Runtime.InteropServices;

namespace Novolis.Raylib.Interop;
/// <summary>Debug-only hooks for automation / diagnostics. Native calls use manifest-defined <see cref = "Raylib6Native"/> entry points.</summary>
internal static partial class RaylibDebugFrameHooks
{
    internal const string CaptureEnvironmentVariable = "NOVOLIS_RAYLIB_DEBUG_CAPTURE";
#if DEBUG
    /// <summary>Invoked on the render thread immediately after <see cref="Raylib6Native.EndDrawing"/> from façade code.</summary>
    public static event Action? AfterEndDrawing;
#endif
    /// <summary>Notify subscribers after the native call named in raylib-debug.manifest.json (<c>notifyAfterNativeCall</c>).</summary>
    internal static void NotifyAfterEndDrawing()
    {
#if DEBUG
        AfterEndDrawing?.Invoke();
#endif
    }

#if DEBUG
    /// <summary>When <see cref="RaylibDebugCaptureGate.ProgrammaticEnabled"/> is set or <see cref="CaptureEnvironmentVariable"/> is <c>1</c>/<c>true</c>/<c>yes</c>, captures the framebuffer to PNG bytes in memory (raylib <c>LoadImageFromScreen</c> / <c>ExportImageToMemory</c>).</summary>
    internal static bool TryCaptureFramePng([System.Diagnostics.CodeAnalysis.NotNullWhen(true)] out byte[]? png)
    {
        png = null;
        if (!RaylibDebugCaptureGate.IsRequested(CaptureEnvironmentVariable))
            return false;

        var image = Raylib6Native.LoadImageFromScreen();
        try
        {
            var ptr = Raylib6Native.ExportImageToMemory(image, ".png", out var size);
            if (ptr == 0 || size <= 0)
                return false;
            png = new byte[size];
            Marshal.Copy(ptr, png, 0, size);
            Raylib6Native.MemFree(ptr);
            return true;
        }
        finally
        {
            Raylib6Native.UnloadImage(image);
        }
    }

#else
    internal static bool TryCaptureFramePng(out byte[]? png)
    {
        png = null;
        return false;
    }
#endif
}
