// <auto-generated />
// Regenerate: dotnet run --project src/Novolis.Raylib.CodeGen -- generate
// ManifestSha256: e05e36aec57ce1c9bb9e85d4b1516dd3b56e34febab18adc4a37b8fbebc2f79e
#nullable enable
using Novolis.Raylib.Interop;
using Novolis.Raylib.Interact;
using System.Runtime.CompilerServices;

namespace Novolis.Raylib.Windowing;
public static partial class Window
{
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    /// <summary>
    /// raylib SetConfigFlags — call before Init for pre-window flags (e.g. WindowStateFlags.Hidden / FLAG_WINDOW_HIDDEN).
    /// </summary>
    public static void SetConfigFlags(uint flags) => Raylib6Native.SetConfigFlags(flags);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void Init(int width, int height, string title) => Raylib6Native.InitWindow(width, height, title);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static bool ShouldClose() => Raylib6Native.WindowShouldClose();
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void Close() => Raylib6Native.CloseWindow();
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static bool IsReady() => Raylib6Native.IsWindowReady();
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static bool IsHidden() => Raylib6Native.IsWindowHidden();
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static int GetScreenWidth() => Raylib6Native.GetScreenWidth();
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static int GetScreenHeight() => Raylib6Native.GetScreenHeight();
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void SetTitle(string title) => Raylib6Native.SetWindowTitle(title);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void ToggleFullscreen() => Raylib6Native.ToggleFullscreen();
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static bool IsFullscreen() => Raylib6Native.IsWindowFullscreen();
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    /// <summary>
    /// raylib SetWindowState (e.g. FLAG_WINDOW_RESIZABLE from raylib headers).
    /// </summary>
    public static void SetState(uint flags) => Raylib6Native.SetWindowState(flags);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void PollInputEvents() => Raylib6Native.PollInputEvents();
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    /// <summary>
    /// Sets the key that closes the window (default Escape / KeyboardKey.Escape).
    /// </summary>
    public static void SetExitKey(KeyboardKey key) => Raylib6Native.SetExitKey((int)key);
}
