// <auto-generated />
// Regenerate: dotnet run --project codegen/Novolis.Raylib.CodeGen -- generate
// ManifestSha256: 3414d24bb780080d0017c425bd7ec2e0353c54aef0598ae22f908c6d8bea1506
#nullable enable
using Novolis.Raylib.Interop;
using Novolis.Raylib.Interact;
using System.Runtime.CompilerServices;

namespace Novolis.Raylib.Windowing;
/// <summary>
/// Window lifecycle, configuration, and display state.
/// </summary>
public static partial class Window
{
    /// <summary>
    /// raylib SetConfigFlags — call before Init for pre-window flags (e.g. WindowStateFlags.Hidden / FLAG_WINDOW_HIDDEN).
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void SetConfigFlags(uint flags) => Raylib6Native.SetConfigFlags(flags);
    /// <summary>
    /// Initialize window and OpenGL context
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void Init(int width, int height, string title) => Raylib6Native.InitWindow(width, height, title);
    /// <summary>
    /// Check if application should close (KEY_ESCAPE pressed or windows close icon clicked)
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static bool ShouldClose() => Raylib6Native.WindowShouldClose();
    /// <summary>
    /// Close window and unload OpenGL context
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void Close() => Raylib6Native.CloseWindow();
    /// <summary>
    /// Check if window has been initialized successfully
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static bool IsReady() => Raylib6Native.IsWindowReady();
    /// <summary>
    /// Check if window is currently hidden
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static bool IsHidden() => Raylib6Native.IsWindowHidden();
    /// <summary>
    /// Get current screen width
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static int GetScreenWidth() => Raylib6Native.GetScreenWidth();
    /// <summary>
    /// Get current screen height
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static int GetScreenHeight() => Raylib6Native.GetScreenHeight();
    /// <summary>
    /// Set title for window
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void SetTitle(string title) => Raylib6Native.SetWindowTitle(title);
    /// <summary>
    /// Toggle window state: fullscreen/windowed, resizes monitor to match window resolution
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void ToggleFullscreen() => Raylib6Native.ToggleFullscreen();
    /// <summary>
    /// Check if window is currently fullscreen
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static bool IsFullscreen() => Raylib6Native.IsWindowFullscreen();
    /// <summary>
    /// raylib SetWindowState (e.g. FLAG_WINDOW_RESIZABLE from raylib headers).
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void SetState(uint flags) => Raylib6Native.SetWindowState(flags);
    /// <summary>
    /// Register all input events
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void PollInputEvents() => Raylib6Native.PollInputEvents();
    /// <summary>
    /// Sets the key that closes the window (default Escape / KeyboardKey.Escape).
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void SetExitKey(KeyboardKey key) => Raylib6Native.SetExitKey((int)key);
}
