// <auto-generated />
// Regenerate: dotnet run --project codegen/Novolis.Raylib.CodeGen -- generate
// ManifestSha256: 79c7b002f4452c27bb6d9b0c9849590d452f3a059113190b28bf2871f063ddbc
#nullable enable
using System.Drawing;
using System.Numerics;
using Novolis.Raylib.Rendering;
using System.Runtime.CompilerServices;

namespace Novolis.Raylib;
/// <summary>
/// Screen-space 2D overlay drawn after World.End (same frame, before EndDrawing).
/// </summary>
public static partial class Hud
{
    /// <summary>
    /// Clears the framebuffer with a color (screen-space HUD; uses ClearBackground).
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void Clear(Color color) => Graphics.ClearBackground(color);
    /// <summary>
    /// Draws text in screen coordinates (HUD overlay).
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void Text(string text, int x, int y, int fontSize, Color color) => Graphics.DrawText(text, x, y, fontSize, color);
    /// <summary>
    /// Measures text width in pixels for HUD layout.
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static int MeasureText(string text, int fontSize) => Graphics.MeasureText(text, fontSize);
    /// <summary>
    /// Filled axis-aligned rectangle in screen space.
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void Rect(int x, int y, int width, int height, Color color) => Graphics.DrawRectangle(x, y, width, height, color);
    /// <summary>
    /// Outlined axis-aligned rectangle in screen space.
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void RectOutline(int x, int y, int width, int height, Color color) => Graphics.DrawRectangleLines(x, y, width, height, color);
    /// <summary>
    /// Filled rectangle from a RectangleF in screen space.
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void RectF(RectangleF rect, Color color) => Graphics.DrawRectangleRec(rect, color);
    /// <summary>
    /// Line segment in screen space.
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void Line(int x1, int y1, int x2, int y2, Color color) => Graphics.DrawLine(x1, y1, x2, y2, color);
    /// <summary>
    /// Filled circle in screen space.
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void Circle(int centerX, int centerY, float radius, Color color) => Graphics.DrawCircle(centerX, centerY, radius, color);
    /// <summary>
    /// Draws a texture at screen position with tint.
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void DrawTexture(Texture texture, int x, int y, Color tint) => Textures.Draw(texture, x, y, tint);
    /// <summary>
    /// Draws a texture region into a destination rectangle (HUD sprites).
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void DrawTexturePro(Texture texture, RectangleF source, RectangleF dest, Vector2 origin, float rotation, Color tint) => Textures.DrawPro(texture, source, dest, origin, rotation, tint);
    /// <summary>
    /// Draws frames-per-second counter at screen position.
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void Fps(int x, int y) => Graphics.DrawFPS(x, y);
}
