// <auto-generated />
// Regenerate: dotnet run --project codegen/Novolis.Raylib.CodeGen -- generate
// ManifestSha256: d6c765a8face80dac5f985910e8875b730bf8698b5fe900ebcc6df9fb5d7ea74
#nullable enable
using System.Drawing;
using System.Numerics;
using Novolis.Raylib.Rendering;
using System.Runtime.CompilerServices;

namespace Novolis.Raylib;
public static partial class Hud
{
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void Clear(Color color) => Graphics.ClearBackground(color);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void Text(string text, int x, int y, int fontSize, Color color) => Graphics.DrawText(text, x, y, fontSize, color);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static int MeasureText(string text, int fontSize) => Graphics.MeasureText(text, fontSize);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void Rect(int x, int y, int width, int height, Color color) => Graphics.DrawRectangle(x, y, width, height, color);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void RectOutline(int x, int y, int width, int height, Color color) => Graphics.DrawRectangleLines(x, y, width, height, color);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void RectF(RectangleF rect, Color color) => Graphics.DrawRectangleRec(rect, color);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void Line(int x1, int y1, int x2, int y2, Color color) => Graphics.DrawLine(x1, y1, x2, y2, color);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void Circle(int centerX, int centerY, float radius, Color color) => Graphics.DrawCircle(centerX, centerY, radius, color);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void DrawTexture(Texture texture, int x, int y, Color tint) => Textures.Draw(texture, x, y, tint);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void DrawTexturePro(Texture texture, RectangleF source, RectangleF dest, Vector2 origin, float rotation, Color tint) => Textures.DrawPro(texture, source, dest, origin, rotation, tint);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void Fps(int x, int y) => Graphics.DrawFPS(x, y);
}
