// <auto-generated />
// Regenerate: dotnet run --project src/Novolis.Raylib.CodeGen -- generate
// ManifestSha256: 83ad574b46f9c6546775c8900e743defa4e6a8ad367f97cc198376cc9b89251b
#nullable enable
using System.Runtime.InteropServices;

namespace Novolis.Raylib.Interop;
internal static unsafe partial class RayguiShimExports
{
    [StructLayout(LayoutKind.Sequential)]
    internal struct RayguiRectangle
    {
        public float X;
        public float Y;
        public float Width;
        public float Height;
    }

    internal static delegate* unmanaged<RayguiRectangle, byte*, int> GuiButton_ptr;
    internal static delegate* unmanaged<RayguiRectangle, byte*, byte*, int> GuiCheckBox_ptr;
    internal static delegate* unmanaged<RayguiRectangle, byte*, int*, int> GuiComboBox_ptr;
    internal static delegate* unmanaged<void> GuiDisable_ptr;
    internal static delegate* unmanaged<RayguiRectangle, byte*, int> GuiDummyRec_ptr;
    internal static delegate* unmanaged<void> GuiEnable_ptr;
    internal static delegate* unmanaged<int> GuiGetState_ptr;
    internal static delegate* unmanaged<int, int, int> GuiGetStyle_ptr;
    internal static delegate* unmanaged<RayguiRectangle, byte*, int> GuiGroupBox_ptr;
    internal static delegate* unmanaged<RayguiRectangle, byte*, int> GuiLabel_ptr;
    internal static delegate* unmanaged<RayguiRectangle, byte*, int> GuiLabelButton_ptr;
    internal static delegate* unmanaged<RayguiRectangle, byte*, int> GuiLine_ptr;
    internal static delegate* unmanaged<void> GuiLoadStyleDefault_ptr;
    internal static delegate* unmanaged<void> GuiLock_ptr;
    internal static delegate* unmanaged<RayguiRectangle, byte*, int> GuiPanel_ptr;
    internal static delegate* unmanaged<RayguiRectangle, byte*, byte*, float*, float, float, int> GuiProgressBar_ptr;
    internal static delegate* unmanaged<float, void> GuiSetAlpha_ptr;
    internal static delegate* unmanaged<int, void> GuiSetState_ptr;
    internal static delegate* unmanaged<int, int, int, void> GuiSetStyle_ptr;
    internal static delegate* unmanaged<RayguiRectangle, byte*, byte*, float*, float, float, int> GuiSlider_ptr;
    internal static delegate* unmanaged<RayguiRectangle, byte*, byte*, float*, float, float, int> GuiSliderBar_ptr;
    internal static delegate* unmanaged<RayguiRectangle, byte*, int> GuiStatusBar_ptr;
    internal static delegate* unmanaged<RayguiRectangle, byte*, byte*, int> GuiToggle_ptr;
    internal static delegate* unmanaged<void> GuiUnlock_ptr;
    internal static bool TryBindShim(nint module, out string? error)
    {
        error = null;
        var pGuiButton = NativeLibrary.GetExport(module, "GuiButton");
        if (pGuiButton == 0)
        {
            error = "Missing export: GuiButton";
            return false;
        }

        GuiButton_ptr = (delegate* unmanaged<RayguiRectangle, byte*, int> )pGuiButton;
        var pGuiCheckBox = NativeLibrary.GetExport(module, "GuiCheckBox");
        if (pGuiCheckBox == 0)
        {
            error = "Missing export: GuiCheckBox";
            return false;
        }

        GuiCheckBox_ptr = (delegate* unmanaged<RayguiRectangle, byte*, byte*, int> )pGuiCheckBox;
        var pGuiComboBox = NativeLibrary.GetExport(module, "GuiComboBox");
        if (pGuiComboBox == 0)
        {
            error = "Missing export: GuiComboBox";
            return false;
        }

        GuiComboBox_ptr = (delegate* unmanaged<RayguiRectangle, byte*, int*, int> )pGuiComboBox;
        var pGuiDisable = NativeLibrary.GetExport(module, "GuiDisable");
        if (pGuiDisable == 0)
        {
            error = "Missing export: GuiDisable";
            return false;
        }

        GuiDisable_ptr = (delegate* unmanaged<void> )pGuiDisable;
        var pGuiDummyRec = NativeLibrary.GetExport(module, "GuiDummyRec");
        if (pGuiDummyRec == 0)
        {
            error = "Missing export: GuiDummyRec";
            return false;
        }

        GuiDummyRec_ptr = (delegate* unmanaged<RayguiRectangle, byte*, int> )pGuiDummyRec;
        var pGuiEnable = NativeLibrary.GetExport(module, "GuiEnable");
        if (pGuiEnable == 0)
        {
            error = "Missing export: GuiEnable";
            return false;
        }

        GuiEnable_ptr = (delegate* unmanaged<void> )pGuiEnable;
        var pGuiGetState = NativeLibrary.GetExport(module, "GuiGetState");
        if (pGuiGetState == 0)
        {
            error = "Missing export: GuiGetState";
            return false;
        }

        GuiGetState_ptr = (delegate* unmanaged<int> )pGuiGetState;
        var pGuiGetStyle = NativeLibrary.GetExport(module, "GuiGetStyle");
        if (pGuiGetStyle == 0)
        {
            error = "Missing export: GuiGetStyle";
            return false;
        }

        GuiGetStyle_ptr = (delegate* unmanaged<int, int, int> )pGuiGetStyle;
        var pGuiGroupBox = NativeLibrary.GetExport(module, "GuiGroupBox");
        if (pGuiGroupBox == 0)
        {
            error = "Missing export: GuiGroupBox";
            return false;
        }

        GuiGroupBox_ptr = (delegate* unmanaged<RayguiRectangle, byte*, int> )pGuiGroupBox;
        var pGuiLabel = NativeLibrary.GetExport(module, "GuiLabel");
        if (pGuiLabel == 0)
        {
            error = "Missing export: GuiLabel";
            return false;
        }

        GuiLabel_ptr = (delegate* unmanaged<RayguiRectangle, byte*, int> )pGuiLabel;
        var pGuiLabelButton = NativeLibrary.GetExport(module, "GuiLabelButton");
        if (pGuiLabelButton == 0)
        {
            error = "Missing export: GuiLabelButton";
            return false;
        }

        GuiLabelButton_ptr = (delegate* unmanaged<RayguiRectangle, byte*, int> )pGuiLabelButton;
        var pGuiLine = NativeLibrary.GetExport(module, "GuiLine");
        if (pGuiLine == 0)
        {
            error = "Missing export: GuiLine";
            return false;
        }

        GuiLine_ptr = (delegate* unmanaged<RayguiRectangle, byte*, int> )pGuiLine;
        var pGuiLoadStyleDefault = NativeLibrary.GetExport(module, "GuiLoadStyleDefault");
        if (pGuiLoadStyleDefault == 0)
        {
            error = "Missing export: GuiLoadStyleDefault";
            return false;
        }

        GuiLoadStyleDefault_ptr = (delegate* unmanaged<void> )pGuiLoadStyleDefault;
        var pGuiLock = NativeLibrary.GetExport(module, "GuiLock");
        if (pGuiLock == 0)
        {
            error = "Missing export: GuiLock";
            return false;
        }

        GuiLock_ptr = (delegate* unmanaged<void> )pGuiLock;
        var pGuiPanel = NativeLibrary.GetExport(module, "GuiPanel");
        if (pGuiPanel == 0)
        {
            error = "Missing export: GuiPanel";
            return false;
        }

        GuiPanel_ptr = (delegate* unmanaged<RayguiRectangle, byte*, int> )pGuiPanel;
        var pGuiProgressBar = NativeLibrary.GetExport(module, "GuiProgressBar");
        if (pGuiProgressBar == 0)
        {
            error = "Missing export: GuiProgressBar";
            return false;
        }

        GuiProgressBar_ptr = (delegate* unmanaged<RayguiRectangle, byte*, byte*, float*, float, float, int> )pGuiProgressBar;
        var pGuiSetAlpha = NativeLibrary.GetExport(module, "GuiSetAlpha");
        if (pGuiSetAlpha == 0)
        {
            error = "Missing export: GuiSetAlpha";
            return false;
        }

        GuiSetAlpha_ptr = (delegate* unmanaged<float, void> )pGuiSetAlpha;
        var pGuiSetState = NativeLibrary.GetExport(module, "GuiSetState");
        if (pGuiSetState == 0)
        {
            error = "Missing export: GuiSetState";
            return false;
        }

        GuiSetState_ptr = (delegate* unmanaged<int, void> )pGuiSetState;
        var pGuiSetStyle = NativeLibrary.GetExport(module, "GuiSetStyle");
        if (pGuiSetStyle == 0)
        {
            error = "Missing export: GuiSetStyle";
            return false;
        }

        GuiSetStyle_ptr = (delegate* unmanaged<int, int, int, void> )pGuiSetStyle;
        var pGuiSlider = NativeLibrary.GetExport(module, "GuiSlider");
        if (pGuiSlider == 0)
        {
            error = "Missing export: GuiSlider";
            return false;
        }

        GuiSlider_ptr = (delegate* unmanaged<RayguiRectangle, byte*, byte*, float*, float, float, int> )pGuiSlider;
        var pGuiSliderBar = NativeLibrary.GetExport(module, "GuiSliderBar");
        if (pGuiSliderBar == 0)
        {
            error = "Missing export: GuiSliderBar";
            return false;
        }

        GuiSliderBar_ptr = (delegate* unmanaged<RayguiRectangle, byte*, byte*, float*, float, float, int> )pGuiSliderBar;
        var pGuiStatusBar = NativeLibrary.GetExport(module, "GuiStatusBar");
        if (pGuiStatusBar == 0)
        {
            error = "Missing export: GuiStatusBar";
            return false;
        }

        GuiStatusBar_ptr = (delegate* unmanaged<RayguiRectangle, byte*, int> )pGuiStatusBar;
        var pGuiToggle = NativeLibrary.GetExport(module, "GuiToggle");
        if (pGuiToggle == 0)
        {
            error = "Missing export: GuiToggle";
            return false;
        }

        GuiToggle_ptr = (delegate* unmanaged<RayguiRectangle, byte*, byte*, int> )pGuiToggle;
        var pGuiUnlock = NativeLibrary.GetExport(module, "GuiUnlock");
        if (pGuiUnlock == 0)
        {
            error = "Missing export: GuiUnlock";
            return false;
        }

        GuiUnlock_ptr = (delegate* unmanaged<void> )pGuiUnlock;
        return true;
    }
}
