// <auto-generated />
// Regenerate: dotnet run --project src/Novolis.Raylib.CodeGen -- generate
// ManifestSha256: da2b9ee7bf01964caba0c2cfe5f93348715d0fd47f55c92675ce0b7521c8ff75
#nullable enable
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
using Novolis.Raylib.Colors;
using Novolis.Raylib.Transformations;

namespace Novolis.Raylib.Interop;
/// <summary>Blittable layout for raylib C struct (generated from manifest).</summary>
[StructLayout(LayoutKind.Sequential)]
internal struct Raylib6NativeImage
{
    public nint Data;
    public int Width;
    public int Height;
    public int Mipmaps;
    public int Format;
}

/// <summary>Low-level raylib 6 entry points (manifest-generated <c>[LibraryImport]</c>).</summary>
internal static partial class Raylib6Native
{
    private const string RaylibDll = "raylib";
    [LibraryImport(RaylibDll)]
    internal static partial void BeginDrawing();
    [LibraryImport(RaylibDll)]
    internal static partial void BeginScissorMode(int x, int y, int width, int height);
    [LibraryImport(RaylibDll)]
    internal static partial void ClearBackground(Color color);
    [LibraryImport(RaylibDll)]
    internal static partial void CloseAudioDevice();
    [LibraryImport(RaylibDll)]
    internal static partial void CloseWindow();
    [LibraryImport(RaylibDll)]
    internal static partial void DrawCircle(int centerX, int centerY, float radius, Color color);
    [LibraryImport(RaylibDll)]
    internal static partial void DrawFPS(int posX, int posY);
    [LibraryImport(RaylibDll)]
    internal static partial void DrawLine(int a, int b, int c, int d, Color color);
    [LibraryImport(RaylibDll)]
    internal static partial void DrawRectangle(int a, int b, int c, int d, Color color);
    [LibraryImport(RaylibDll)]
    internal static partial void DrawRectangleLines(int a, int b, int c, int d, Color color);
    [LibraryImport(RaylibDll)]
    internal static partial void DrawRectangleRec(Rectangle rec, Color color);
    [LibraryImport(RaylibDll)]
    internal static partial void DrawText([MarshalUsing(typeof(Utf8StringMarshaller))] string text, int posX, int posY, int fontSize, Color color);
    [LibraryImport(RaylibDll)]
    internal static partial void EndDrawing();
    [LibraryImport(RaylibDll)]
    internal static partial void EndScissorMode();
    [LibraryImport(RaylibDll)]
    internal static partial nint ExportImageToMemory(Raylib6NativeImage image, [MarshalUsing(typeof(Utf8StringMarshaller))] string fileType, out int fileSize);
    [LibraryImport(RaylibDll)]
    internal static partial int GetCharPressed();
    [LibraryImport(RaylibDll)]
    internal static partial float GetFrameTime();
    [LibraryImport(RaylibDll)]
    internal static partial int GetKeyPressed();
    [LibraryImport(RaylibDll)]
    internal static partial Vector2 GetMouseDelta();
    [LibraryImport(RaylibDll)]
    internal static partial Vector2 GetMousePosition();
    [LibraryImport(RaylibDll)]
    internal static partial float GetMouseWheelMove();
    [LibraryImport(RaylibDll)]
    internal static partial int GetScreenHeight();
    [LibraryImport(RaylibDll)]
    internal static partial int GetScreenWidth();
    [LibraryImport(RaylibDll)]
    internal static partial void InitAudioDevice();
    [LibraryImport(RaylibDll)]
    internal static partial void InitWindow(int width, int height, [MarshalUsing(typeof(Utf8StringMarshaller))] string title);
    [LibraryImport(RaylibDll)]
    [return: MarshalAs(UnmanagedType.I1)]
    internal static partial bool IsCursorOnScreen();
    [LibraryImport(RaylibDll)]
    [return: MarshalAs(UnmanagedType.I1)]
    internal static partial bool IsKeyDown(int key);
    [LibraryImport(RaylibDll)]
    [return: MarshalAs(UnmanagedType.I1)]
    internal static partial bool IsKeyPressed(int key);
    [LibraryImport(RaylibDll)]
    [return: MarshalAs(UnmanagedType.I1)]
    internal static partial bool IsKeyReleased(int key);
    [LibraryImport(RaylibDll)]
    [return: MarshalAs(UnmanagedType.I1)]
    internal static partial bool IsMouseButtonDown(int key);
    [LibraryImport(RaylibDll)]
    [return: MarshalAs(UnmanagedType.I1)]
    internal static partial bool IsMouseButtonPressed(int key);
    [LibraryImport(RaylibDll)]
    [return: MarshalAs(UnmanagedType.I1)]
    internal static partial bool IsWindowFullscreen();
    [LibraryImport(RaylibDll)]
    [return: MarshalAs(UnmanagedType.I1)]
    internal static partial bool IsWindowHidden();
    [LibraryImport(RaylibDll)]
    [return: MarshalAs(UnmanagedType.I1)]
    internal static partial bool IsWindowReady();
    [LibraryImport(RaylibDll)]
    internal static partial Raylib6NativeImage LoadImageFromScreen();
    [LibraryImport(RaylibDll)]
    internal static partial int MeasureText([MarshalUsing(typeof(Utf8StringMarshaller))] string text, int fontSize);
    [LibraryImport(RaylibDll)]
    internal static partial void MemFree(nint ptr);
    [LibraryImport(RaylibDll)]
    internal static partial void PollInputEvents();
    [LibraryImport(RaylibDll)]
    internal static partial void SetConfigFlags(uint flags);
    [LibraryImport(RaylibDll)]
    internal static partial void SetExitKey(int value);
    [LibraryImport(RaylibDll)]
    internal static partial void SetTargetFPS(int value);
    [LibraryImport(RaylibDll)]
    internal static partial void SetTraceLogLevel(int value);
    [LibraryImport(RaylibDll)]
    internal static partial void SetWindowState(uint flags);
    [LibraryImport(RaylibDll)]
    internal static partial void SetWindowTitle([MarshalUsing(typeof(Utf8StringMarshaller))] string title);
    [LibraryImport(RaylibDll)]
    internal static partial void ToggleFullscreen();
    [LibraryImport(RaylibDll)]
    internal static partial void UnloadImage(Raylib6NativeImage image);
    [LibraryImport(RaylibDll)]
    [return: MarshalAs(UnmanagedType.I1)]
    internal static partial bool WindowShouldClose();
}
