// <auto-generated />
// Regenerate: dotnet run --project src/Novolis.Raylib.CodeGen -- generate
// ManifestSha256: c452513a01b2f50d03d0947a639b7194a930c095728897ea5ab6ffb0f88ede73
#nullable enable
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
using Novolis.Raylib.Colors;
using Novolis.Raylib.Transformations;

namespace Novolis.Raylib.Interop;
/// <summary>Blittable layout for raylib C struct (generated from manifest).</summary>
[StructLayout(LayoutKind.Sequential)]
internal struct Raylib6NativeImage
{
    public nint Data;
    public int Width;
    public int Height;
    public int Mipmaps;
    public int Format;
}

/// <summary>Blittable layout for raylib C struct (generated from manifest).</summary>
[StructLayout(LayoutKind.Sequential)]
internal struct Raylib6NativeTexture
{
    public uint Id;
    public int Width;
    public int Height;
    public int Mipmaps;
    public int Format;
}

/// <summary>Low-level raylib 6 entry points (manifest-generated <c>[LibraryImport]</c>).</summary>
internal static partial class Raylib6Native
{
    private const string RaylibDll = "raylib";
    [LibraryImport(RaylibDll)]
    internal static partial void BeginDrawing();
    [LibraryImport(RaylibDll)]
    internal static partial void BeginMode3D(Camera3D camera);
    [LibraryImport(RaylibDll)]
    internal static partial void BeginScissorMode(int x, int y, int width, int height);
    [LibraryImport(RaylibDll)]
    internal static partial void ClearBackground(Color color);
    [LibraryImport(RaylibDll)]
    internal static partial void CloseAudioDevice();
    [LibraryImport(RaylibDll)]
    internal static partial void CloseWindow();
    [LibraryImport(RaylibDll)]
    internal static partial void DisableCursor();
    [LibraryImport(RaylibDll)]
    internal static partial void DrawCircle(int centerX, int centerY, float radius, Color color);
    [LibraryImport(RaylibDll)]
    internal static partial void DrawCube(Vector3 position, float width, float height, float length, Color color);
    [LibraryImport(RaylibDll)]
    internal static partial void DrawCubeV(Vector3 position, Vector3 size, Color color);
    [LibraryImport(RaylibDll)]
    internal static partial void DrawCubeWiresV(Vector3 position, Vector3 size, Color color);
    [LibraryImport(RaylibDll)]
    internal static partial void DrawCylinder(Vector3 position, float radiusTop, float radiusBottom, float height, int slices, Color color);
    [LibraryImport(RaylibDll)]
    internal static partial void DrawFPS(int posX, int posY);
    [LibraryImport(RaylibDll)]
    internal static partial void DrawGrid(int slices, float spacing);
    [LibraryImport(RaylibDll)]
    internal static partial void DrawLine(int a, int b, int c, int d, Color color);
    [LibraryImport(RaylibDll)]
    internal static partial void DrawLine3D(Vector3 position, Vector3 size, Color color);
    [LibraryImport(RaylibDll)]
    internal static partial void DrawRectangle(int a, int b, int c, int d, Color color);
    [LibraryImport(RaylibDll)]
    internal static partial void DrawRectangleLines(int a, int b, int c, int d, Color color);
    [LibraryImport(RaylibDll)]
    internal static partial void DrawRectangleRec(Rectangle rec, Color color);
    [LibraryImport(RaylibDll)]
    internal static partial void DrawSphere(Vector3 centerPos, float radius, Color color);
    [LibraryImport(RaylibDll)]
    internal static partial void DrawSphereWires(Vector3 centerPos, float radius, int rings, int slices, Color color);
    [LibraryImport(RaylibDll)]
    internal static partial void DrawText([MarshalUsing(typeof(Utf8StringMarshaller))] string text, int posX, int posY, int fontSize, Color color);
    [LibraryImport(RaylibDll)]
    internal static partial void DrawTexture(Raylib6NativeTexture texture, int posX, int posY, Color tint);
    [LibraryImport(RaylibDll)]
    internal static partial void DrawTexturePro(Raylib6NativeTexture texture, Rectangle source, Rectangle dest, Vector2 origin, float rotation, Color tint);
    [LibraryImport(RaylibDll)]
    internal static partial void EnableCursor();
    [LibraryImport(RaylibDll)]
    internal static partial void EndDrawing();
    [LibraryImport(RaylibDll)]
    internal static partial void EndMode3D();
    [LibraryImport(RaylibDll)]
    internal static partial void EndScissorMode();
    [LibraryImport(RaylibDll)]
    internal static partial nint ExportImageToMemory(Raylib6NativeImage image, [MarshalUsing(typeof(Utf8StringMarshaller))] string fileType, out int fileSize);
    [LibraryImport(RaylibDll)]
    internal static partial int GetCharPressed();
    [LibraryImport(RaylibDll)]
    internal static partial float GetFrameTime();
    [LibraryImport(RaylibDll)]
    internal static partial int GetKeyPressed();
    [LibraryImport(RaylibDll)]
    internal static partial Vector2 GetMouseDelta();
    [LibraryImport(RaylibDll)]
    internal static partial Vector2 GetMousePosition();
    [LibraryImport(RaylibDll)]
    internal static partial float GetMouseWheelMove();
    [LibraryImport(RaylibDll)]
    internal static partial int GetScreenHeight();
    [LibraryImport(RaylibDll)]
    internal static partial int GetScreenWidth();
    [LibraryImport(RaylibDll)]
    internal static partial void InitAudioDevice();
    [LibraryImport(RaylibDll)]
    internal static partial void InitWindow(int width, int height, [MarshalUsing(typeof(Utf8StringMarshaller))] string title);
    [LibraryImport(RaylibDll)]
    [return: MarshalAs(UnmanagedType.I1)]
    internal static partial bool IsCursorOnScreen();
    [LibraryImport(RaylibDll)]
    [return: MarshalAs(UnmanagedType.I1)]
    internal static partial bool IsKeyDown(int key);
    [LibraryImport(RaylibDll)]
    [return: MarshalAs(UnmanagedType.I1)]
    internal static partial bool IsKeyPressed(int key);
    [LibraryImport(RaylibDll)]
    [return: MarshalAs(UnmanagedType.I1)]
    internal static partial bool IsKeyReleased(int key);
    [LibraryImport(RaylibDll)]
    [return: MarshalAs(UnmanagedType.I1)]
    internal static partial bool IsMouseButtonDown(int key);
    [LibraryImport(RaylibDll)]
    [return: MarshalAs(UnmanagedType.I1)]
    internal static partial bool IsMouseButtonPressed(int key);
    [LibraryImport(RaylibDll)]
    [return: MarshalAs(UnmanagedType.I1)]
    internal static partial bool IsTextureValid(Raylib6NativeTexture texture);
    [LibraryImport(RaylibDll)]
    [return: MarshalAs(UnmanagedType.I1)]
    internal static partial bool IsWindowFullscreen();
    [LibraryImport(RaylibDll)]
    [return: MarshalAs(UnmanagedType.I1)]
    internal static partial bool IsWindowHidden();
    [LibraryImport(RaylibDll)]
    [return: MarshalAs(UnmanagedType.I1)]
    internal static partial bool IsWindowReady();
    [LibraryImport(RaylibDll)]
    internal static partial Raylib6NativeImage LoadImageFromScreen();
    [LibraryImport(RaylibDll)]
    internal static partial Raylib6NativeTexture LoadTexture([MarshalUsing(typeof(Utf8StringMarshaller))] string fileName);
    [LibraryImport(RaylibDll)]
    internal static partial int MeasureText([MarshalUsing(typeof(Utf8StringMarshaller))] string text, int fontSize);
    [LibraryImport(RaylibDll)]
    internal static partial void MemFree(nint ptr);
    [LibraryImport(RaylibDll)]
    internal static partial void PollInputEvents();
    [LibraryImport(RaylibDll)]
    internal static partial void SetConfigFlags(uint flags);
    [LibraryImport(RaylibDll)]
    internal static partial void SetExitKey(int value);
    [LibraryImport(RaylibDll)]
    internal static partial void SetMousePosition(int posX, int posY);
    [LibraryImport(RaylibDll)]
    internal static partial void SetTargetFPS(int value);
    [LibraryImport(RaylibDll)]
    internal static partial void SetTraceLogLevel(int value);
    [LibraryImport(RaylibDll)]
    internal static partial void SetWindowState(uint flags);
    [LibraryImport(RaylibDll)]
    internal static partial void SetWindowTitle([MarshalUsing(typeof(Utf8StringMarshaller))] string title);
    [LibraryImport(RaylibDll)]
    internal static partial void ToggleFullscreen();
    [LibraryImport(RaylibDll)]
    internal static partial void UnloadImage(Raylib6NativeImage image);
    [LibraryImport(RaylibDll)]
    internal static partial void UnloadTexture(Raylib6NativeTexture texture);
    [LibraryImport(RaylibDll)]
    [return: MarshalAs(UnmanagedType.I1)]
    internal static partial bool WindowShouldClose();
}
