// <auto-generated />
// Regenerate: dotnet run --project codegen/Novolis.Raylib.CodeGen -- generate
// ManifestSha256: c5e666aec25c3034bc5d2639dfce85ebd4bbda7b7c587047807104cb5129bf3b
#nullable enable
using Novolis.Raylib.Interop;
using System.Runtime.CompilerServices;

namespace Novolis.Raylib.Audio;
public static partial class AudioDevice
{
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void Init() => Raylib6Native.InitAudioDevice();
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void Close() => Raylib6Native.CloseAudioDevice();
}
